### ISSUE TITLE
(S) IPA Server- Investigate what we need to do

### ISSUE THREAD

**Issue by sfinn85** [fedora-infra/noggin#1]
**Acceptance Criteria:** 

- Identify/ document what we need to do
- List of steps

**Definition of done:**
All of the above completed

**Comment by relrod** [comment]
I've spoken with Christian on the IPA team.

EL 8.2 will have a [new enough IPA](https://bugzilla.redhat.com/show_bug.cgi?id=1748987) that has the features we need added.

The recommended approach is to set up an el8.2 replica against the current prod IPA servers, let everything sync over, and then kill the el7 servers. That will get us to a version of IPA that works for us without having to do any exporting/reimporting/etc.

**Comment by relrod** [comment]
So this is technically blocked on el8.2 but that should be out RSN.

**Comment by sfinn85** [comment]
Hi @relrod 

This story is to investigate what we need to do. It seems like you have done that by noting your recommended approach " The recommended approach is to set up an el8.2 replica against the current prod IPA servers, let everything sync over, and then kill the el7 servers. That will get us to a version of IPA that works for us without having to do any exporting/reimporting/etc." 

Would you like to move this to review, to allow a team member to review the recommended approach?

The actual work on the IPA server will need to be created as another user story. 

Thoughts?

Sarah
