### ISSUE TITLE
As a registered user, I want to be able to leave a group that I currently am a member of

### ISSUE THREAD

**Issue by abompard** [fedora-infra/noggin#108]
Current FAS allows a user to leave a group, securitas should too.

**Comment by abompard** [comment]
There's already a list of groups on the user profile, so it should be easy to add a "leave" button there. We just need to be careful of group sponsors: we assume that a sponsor is also a member (see [controller/group.py line 25](https://github.com/fedora-infra/securitas/blob/master/securitas/controller/group.py#L25), so just removing a sponsor's membership will leave it as a `membermanager` in IPA, and we probably don't want securitas to be touching membermanagers (sponsors). @relrod, do you envision the `ipa_admin` user being able to remove a membermanager from a group?

I'd go with Medium because of this corner case.

Acceptance criteria:
- A user is able to remove themselves from a group
- A user can't remove someone else from their groups just by going to their profile page
- If a user quits a group they are a sponsor of, they will also be removed from the sponsors list of that group (to check with @relrod ) Checked - not in scope of securitas so not valid for AC

DoD:
- Acceptance criteria are met
- 100% code coverage

**Comment by ryanlerch** [comment]
@relrod @abompard is it in the scope of securitas to manage membermanagers (i.e. sponsors)? I assumed that this was to be done by admins, like the group details themselves.

Note, that it is possible in freeIPA for a user to be a membermanager, but not a member of a group. However the group view only displays membermanagers (sponsors) that are also members. Howwever, if a user is a membermanager, but not a member, they can still remove other members.

**Comment by relrod** [comment]
> @relrod @abompard is it in the scope of securitas to manage membermanagers (i.e. sponsors)?

No

> I assumed that this was to be done by admins, like the group details themselves.

Correct

**Comment by ryanlerch** [comment]
SO if a user that is a membermanager removes themselves (or is removed) as a member of a group, they should remain a membermanager until an admin removes them?

**Comment by tiran** [comment]
By default users cannot remove themselves from a group. Only member managers or privileged users can remove a user. I'd have to add a new ACI to allow self-removal. Adding or removing a user from a group is controlled by the same permission type ``write``. This makes it a bit more complicated to define an ACI.

This ACI should do the trick.

```
(targetattr = "member")(targetfilter = "(objectclass=ipaUserGroup)")(version 3.0; acl "Allow member to remove themselves"; allow (selfwrite) userattr = "member#USERDN";)
```

It allows self-write to member attribute of IPA user groups if the group's member attribute contains the user's DN. ``selfwrite`` prevents the user from adding/removing other users. ``userattr = "member#USERDN"`` only allows writes when the user is a member of the group.

The ACI applies to all groups. It's possible to define a custom group object class and add a flag to limit the capability to some groups.

**Comment by relrod** [comment]
> SO if a user that is a membermanager removes themselves (or is removed) as a member of a group, they should remain a membermanager until an admin removes them?

Or the portal will need to use an elevated user (called `ipa_admin` internally in Securitas, even though the user should NOT have full IPA admin privileges, just a few escalated privileges), to remove the user from the group's membermanagers as well. @tiran does that seem like the way forward here?

**Comment by tiran** [comment]
You don't need a privileged account. The feature can be implemented with an additional ACI and an additional post callback for ``group_remove_member``. We need an ACI similar to the self-removal ACI but for member managers. I think this should work (untested):

```
(targetattr = "memberManager")(targetfilter = "(objectclass=ipaUserGroup)")(version 3.0; acl "Allow member managers to remove themselves"; allow (selfwrite) userattr = "memberManager#USERDN";)
```

The callback for ``group_remove_member.register_post_callback()`` has to call ``group_remove_membermanager``.

That should do the trick.
