### ISSUE TITLE
Client-side validation of OTP field on login form

### ISSUE THREAD

**Issue by jn64** [fedora-infra/noggin#1152]
[`pattern` attribute can be set for client-side validation (depending on browser support)](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input#pattern).

For example `pattern="\d{6}"` for 6-digit OTPs (I'm not sure what types of OTP are supported by noggin). The form submission will be blocked if the input does not match the pattern.

If the user mis-types the OTP, this saves them from having to re-fill the username and password if they had submitted and failed the server-side validation.

Screenshot showing client-side validation of OTP field in Firefox, preventing submission of wrong OTP:

![Screenshot showing client-side validation of OTP field in Firefox](https://user-images.githubusercontent.com/23169302/221774808-22bb6a4e-1414-4c8c-8e39-56fb2fcd2588.png)

**Comment by abompard** [comment]
Pretty cool, thanks for the detailed issue!

**Comment by jn64** [comment]
Sorry, I must have followed a link to an older commit when I was browsing the repo earlier, because the [`autocomplete=off` is already implemented in dev branch](https://github.com/fedora-infra/noggin/blob/dev/noggin/templates/_login_form.html). I will edit the issue to be about the client-side validation only.

**Comment by emergenitro** [comment]
Hello!

May I take up this issue? Also, Noggin does in fact use 6-digit OTPs.
