### ISSUE TITLE
As a registered user, I want to prevent attackers from changing my password.

### ISSUE THREAD

**Issue by Rombobeorn** [fedora-infra/noggin#117]
If somebody tries to take over my account by requesting a password reset and intercepting the password reset email, then I want the content of that email to be useless to everyone but me.

Current FAS allows me to register an OpenPGP key ID and says that it can be used when a password reset email is sent. I would like to see this feature carried over, but with one change: Users should be allowed to upload their actual key, not just a key ID. The primary reason is that users shouldn't be required to understand the difference between a 32-bit key ID, which is insecure, a 64-bit key ID, and a fingerprint.

If no key has been uploaded, then the system could try a WKD and/or DNS lookup to find a key for the user's email address:
https://wiki.gnupg.org/WKD
https://tools.ietf.org/html/draft-koch-openpgp-webkey-service-09
https://tools.ietf.org/html/rfc7929

If the user hasn't published a key in WKD or DNS either, then the system should fall back on sending an unprotected password reset email. If an error prevents looking up a key, then a password reset email should not be sent because it may be an attempt at a downgrade attack. Instead the user should be notified and given enough details to have a chance to do something about the error.

I may be able to help with interfacing with GnuPG, although I know next to nothing about Flask or FreeIPA.

**Comment by relrod** [comment]
Current FAS won't encrypt password reset emails. What is meant there is that if a user loses access to their email address and needs to reset their password, then at an admin's discretion, the user can sign/encrypt an email with that same key, to verify their identity in another way.

This isn't an automatic process.
