### ISSUE TITLE
"Private" checkbox on profile page not working.

### ISSUE THREAD

**Issue by piano1029** [fedora-infra/noggin#1202]
The private checkbox on the edit profile page doesn't work, when saving and not modifying anything else it gives the error "no modifications to be performed". When saving and modifying something else it does appear to be saved, but when going back to the profile and going back to the edit profile page it just becomes unchecked again.

**Comment by mh21** [comment]
I hit a similar (same?) problem today. For me, the displayed checkbox state was always off, independent of profile visibility. But checking it did set the profile to private, as leaving it unchecked switched it back to public.
