### ISSUE TITLE
Deployment Docs?

### ISSUE THREAD

**Issue by duaneking** [fedora-infra/noggin#1289]
Filing this bug because there is no documentation on how to deploy this. And when I check the official documentation, it just has a giant "to do".

I'm interested in learning more about this and possibly helping the community with code. But I cannot do that unless I can deploy it, And there's no instructions or documentation on how to do that according to the docs based on what I can find.

**Comment by duaneking** [comment]
https://noggin-aaa.readthedocs.io/en/latest/installation.html Literally just says "to do"

**Comment by abompard** [comment]
Indeed, thanks for reporting. I suppose someone could piece together the installation docs from the ansible repository that is used to install Noggin in the Vagrant development environment, in `devel/ansible`. Hopefully someone will have the courage and dedication to do this! :wink:

**Comment by Cliftonz** [comment]
@duaneking We have been asking for about 2 years over here https://github.com/fedora-infra/noggin/issues/332

**Comment by Cliftonz** [comment]
@abompard  Just so you are aware @Conan-Kudo  says he made some progress on this but I am unaware if it is pushed or not.

**Comment by duaneking** [comment]
So this project is unmaintained and has been abandoned?

Am I to assume that fedora is dead in favor of Rocky Linux, then?

**Comment by Cliftonz** [comment]
@duaneking I do not think this project is abandoned they just had a release 2 weeks ago, however they just have not dedicated time to DX on the deployment side of things to make high quality documentation.

As they say, "If its not documented, I does not exist"

**Comment by duaneking** [comment]
That's exactly it; The fact that it's not documented means it doesn't exist.

You can't tell an entire community of people that they "have to ask questions the right way", and as part of that give them the idea that reading the documentation is the first critical step, and then not have docs available.

It's things like this that make people like me choose to support Rocky Linux over Fedora, because at least they seem to care about onboarding devs.

I'm not getting that impression from fedora based on the lack of documentation, that and the fact that it seems a security audit is being blocked by this, that has been blocked for over two years, if I'm reading the information correctly.

The more I read on that, the less I want to use fedora, or support it, and it's really sad to see fedora doesn't consider security to be a priority enough that they're willing to unblock things to make sure it's considered a priority, so I think I'm just going to use this time for other things and maybe in the future support Rocky Linux, thanks. It honestly doesn't look to me like fedora cares about security anymore if they're willing to block a security audit for over two years simply because somebody can't be troubled to write a quickstart.

To be honest, This is insane, and I have to consider fedora dead now, because if you're willing to publicly block security audits for years,  that tells me that fedora doesn't take security seriously, and even if that's not true, the optics are so bad that I can't trust it anymore based on what I'm seeing with this thread alone.

**Comment by Conan-Kudo** [comment]
I shipped a quick start guide in the Fedora package: https://src.fedoraproject.org/rpms/noggin/blob/rawhide/f/noggin-README.Fedora

**Comment by Cliftonz** [comment]
@Conan-Kudo Thanks for doing this!

Sounds like we can close this issue then! I would just make sure to add this into the docs or add a link to the package so people will know where to look.

Thanks again!

**Comment by abompard** [comment]
I'm pretty sure the security audit happened 2 years ago, the ticket probably wasn't updated.

**Comment by abompard** [comment]
I agree that the README.Fedora content should be at least linked to from the Noggin docs. I think I'll just copy-paste it, if that's fine with you @Conan-Kudo .

**Comment by abompard** [comment]
That said, @duaneking , I do not appreciate the attempt to shame or blackmail maintainers into doing the work you want to see done. This behavior is most likely to create reactance at best, burnout at worst.
I think it would have been preferable to use the energy to just do it and submit a PR. It would have contributed to the project and the community in a more fruitful way than making a grand claim that Fedora is dead because its accounts frontend has no installation docs.
