### ISSUE TITLE
As a group owner, i want to approve requests to join a group

### ISSUE THREAD

**Issue by sfinn85** [fedora-infra/noggin#13]

**Comment by ryanlerch** [comment]
@sfinn85 @relrod this one is possibly out of scope / and or not even needed in securitas. Suggest closing?

**Comment by sfinn85** [comment]
Is this currently available on FAS or is it an add on with Securitas? @relrod @abompard

**Comment by abompard** [comment]
The feature is in FAS but I think we plan on letting group owners do it in FreeIPA's UI directly? Is that right?

**Comment by sfinn85** [comment]
Ok so from my understanding this is currently a feature but we were looking at improving the UI. I think at this point, this could be a ' nice to have' .
Let's close it, for now if we feel this needs to be improved we can do this after go live.
