### ISSUE TITLE
Register account not working

### ISSUE THREAD

**Issue by Daijobou** [fedora-infra/noggin#1333]
I get

> We could not send you the address validation email, please retry later

After "Resend mail"-Button

> The address validation email has be sent again. Make sure it did not land in your spam folder

But no mail is coming for hours (spam folder not exists). After reload page and click "resend mail" again both messages appear.

email-address was "info@[placeholder].com".

**Comment by ryanlerch** [comment]
Hi, was this resolved?

are you able to give some more information, primarily the username that you tried to register?

**Comment by Daijobou** [comment]
No, I tried different usernames, same e-mail-address. After 2 months I have no idea was the usernames was, however there was a issue with "mail", not usernames. :)
I close this ticket.
