### ISSUE TITLE
Creating account: no email sent

### ISSUE THREAD

**Issue by mvieth** [fedora-infra/noggin#1393]
Hi, I have a problem when creating an account on accounts.fedoraproject.org. Basically, I receive no validation email. I am totally sure I entered the correct email address. I checked my spam folder, still nothing. I hit "Resend email" twice and waited for hours, but still no email (I did see the pop-up "The address validation email has be sent again. Make sure it did not land in your spam folder" on the website). I don't know what I could have done wrong. If it matters: my email address is of the format `abc.def@g-hij.kl`. Thanks in advance.

**Comment by ryanlerch** [comment]
Hi, I just checked and email validation is working for me.

Might be worth filing this ticket at https://pagure.io/fedora-infrastructure/issues -- they might be able to track down the issue on that side.

**Comment by mvieth** [comment]
@ryanlerch In the meantime, I was able to create an account with a different email address (a `gmail.com` address). With that address, validation worked without a problem. I suspect that only specific characters in the address cause a problem, maybe the hyphen?
