### ISSUE TITLE
As an application owner, I want a fedora-messaging message to be emitted when a user is created

### ISSUE THREAD

**Issue by abompard** [fedora-infra/noggin#141]
We need the portal to emit a message when a user registers, because the Badges application uses it. FAS used to emit a message on the `fas.user.create` topic, the contents could be modelled after it (or adapted).

**Acceptance Criteria**:
- a Fedora Messaging message is emitted when a user is registered
- to ease transition and if it's possible, the message should be emitted on the same topic with the same content.
- a crash in the message sending code should cause a message to be logged with full traceback, but the page should not fail rendering.

**Definition of Done**:
- all the above is done
- unit tests for 100% coverage (unless explicitely ignored with an explanation)
- CI passes
- the path to the Fedora Messaging configuration can be set by a configuration variable.
- the message should use [schemas](https://fedora-messaging.readthedocs.io/en/stable/messages.html)
- there is documentation on the message schema and its contents

**Comment by ryanlerch** [comment]
Waiting on issue #141 and PR #146 to go through before continuing on this one.
