### ISSUE TITLE
Rename the project to a legally available name

### ISSUE THREAD

**Issue by abompard** [fedora-infra/noggin#142]
Securitas is not available as a name for this project, we need to rename it. What needs to be renamed:

- [x] the github project
- [x] all references of securitas in the source code
- [x] the Centos CI project
- [x] the mergify integration
- [x] the readthedocs integration and associated webhooks
- [x] the LGTM / Sonarqube integrations
- [ ] the Communishift project and associated webhooks
- [x] the bot that publishes on the IRC channel

**Comment by abompard** [comment]
I think I'm the only one that has the permissions to do all that so I might as well do it.

**Comment by sfinn85** [comment]
Waiting on legal to revert back :)

**Comment by abompard** [comment]
All checkboxes have been ticked, but I still see the CentOS CI project as being "securitas": https://jenkins-fedora-apps.apps.ci.centos.org/job/securitas/

Is it actually done? Could all checkboxes have been auto-ticked when the PR was merged?

**Comment by StephenCoady** [comment]
@abompard this is definitely my fault, sorry about that. This shouldn't have been closed and I'm not sure what happened with the tick boxes. Will rectify.

**Comment by abompard** [comment]
Since Communishift is going to be shut down, we'll recreate the project with the right name when it's back up. All the rest is done.
