### ISSUE TITLE
As a user, i want to join / request to join a group

### ISSUE THREAD

**Issue by sfinn85** [fedora-infra/noggin#15]

**Comment by ryanlerch** [comment]
@relrod is this one valid? IIRC, the idea here is that a group sponsor just adds a user to the group. there is no longer going to be a concept of requesting a group membership.

AIUI, the workflow here is the user requests access to a group via other means, like the group email list or whatever.

**Comment by relrod** [comment]
@ryanlerch correct, this ticket is just for tracking and noting that. No action needed.
