### ISSUE TITLE
As a User, I want to be able to resync an OTP token, so that I can keep using it

### ISSUE THREAD

**Issue by abompard** [fedora-infra/noggin#150]
**Acceptance Criteria**
- the page should **not** be authenticated
- it should use the `otptoken_sync` API call

**Definition of Done**
- All of the above works
- Unit tests with 100% coverage
- Documentation is written
- CI passes

**Comment by StephenCoady** [comment]
Leaving an update here as I am not here tomorrow (Tuesday).

I have implemented the controller logic and views for this and it is working well. Writing the tests at the moment. 

cc @abompard @ryanlerch

**Comment by StephenCoady** [comment]
This is ready for review. Only one comment on the AC: the `otptoken_sync` endpoint doesn't exist so I made the call manually instead.
