### ISSUE TITLE
As a User, I want to have a process to recover my account if I have enabled 2FA and lost my token

### ISSUE THREAD

**Issue by abompard** [fedora-infra/noggin#151]
There should be a page (or a box on a page) that explains what to do when a user has lost their token. Currently, if a GPG key has been declared, they must send a signed email to Fedora admins with their request.

I propose that we mandate having a GPG key setup to enable 2FA. But we still need to think about the cases where a user with 2FA would have no GPG key (because it was expired or revoked maybe).

@relrod , @nirik , @puiterwijk  do you have an opinion?

**Comment by abompard** [comment]
Hey @puiterwijk or @nirik , does this proposition suit you? What do you think we should do with the outliers?

**Comment by puiterwijk** [comment]
Make them email admin@fp.o and then the admins will have to manually process it.

**Comment by puiterwijk** [comment]
Yes, that will take a lot longer. But this is a very specific case where any automated system would be a major risk of 2fa-bypass.

**Comment by abompard** [comment]
Thanks, will do!

- #155 ensures that the last GPG ID can't be removed is the user has an OTP token
- #147 ensures that there is a GPG ID before enrolling an OTP token

So this ticket is about outliers.

**Acceptance criteria**
- the login page should link to a page or display a box explaining what to do if the last/only token is lost
- this piece of information should tell users to email admin@fp.o with a signed email (if possible), and let the admins handle the request.

**DoD**
- All AC are met
- The page follows the application's style

**Comment by Conan-Kudo** [comment]
Why wouldn't you have an automated flow for this?

One way to conceive this would be to use some other second factor as a way to verify this. For example, one of the systems I use sends me an email that clicks me through an OTP second factor to allow me to reset my MFA settings. That's about as secure as emailing someone and waiting for them to manually do something about it.

(This effectively does a "what you have" factor test along with the "what you know" factor that is your password).

**Comment by Conan-Kudo** [comment]
> Yes, that will take a lot longer. But this is a very specific case where any automated system would be a major risk of 2fa-bypass.

I think you are massively overthinking this. The value in 2FA is that there's more than one factor (that is, more factors than "what you know", e.g. a password). Beyond that, it's *really* not important. 

If the user has lost their 2FA token, there are a number of other alternatives to dealing with that. Most systems do backup codes to allow reset. Some systems do as I suggested in the previous comment and generate an OTP second factor via an email that you click through, limited to forcing an MFA reset.

I lean towards the latter, as that's useful for *any* account recovery flow.

**Comment by tiran** [comment]
IPA does not support recovery codes. You can implement a poor man's replacement with a HOTP token (counter based). With HOTP users have to use the recovery tokens in order. If the user uses recovery token 5, then 1-4 are rendered invalid, too.

**Comment by Conan-Kudo** [comment]
That seems like a pretty big weakness there... Is it on the IPA roadmap to fix that?

**Comment by tiran** [comment]
> That seems like a pretty big weakness there... Is it on the IPA roadmap to fix that?

The OTP workflow is designed for ~cooperate~ corporate environments with a tighter feedback cycle between users and admins. If you loose your last OTP token you typically have to proof your identity in some other way.

I'm not aware of a feature request for recovery codes. They are not on our roadmap yet.

**Comment by Conan-Kudo** [comment]
> The OTP workflow is designed for cooperate environments with a tighter feedback cycle between users and admins.

I presume you mean "corporate environments", and in that mindset, it totally makes sense. It's just not useful for this use-case. Would it be possible to get something on the roadmap to resolve this particular issue, or is there a way you can think to work around that problem to implement a more self-service workflow for this?

**Comment by tiran** [comment]
Yes, please open a feature request on [Pagure](https://pagure.io/freeipa) and describe how recovery codes should behave. It might be possible to implement them on top of existing HOTP or we may have to introduce a new token type.

**Comment by Conan-Kudo** [comment]
@tiran I've filed it as https://pagure.io/freeipa/issue/8235

**Comment by nirik** [comment]
I also would like to automate this, but it's tricky. 
The email with a reset token works fine if we assume whoever controls the email is the user. 
Recovery codes could work, but what if the user never saved them/lost those too?
Security questions could work, but again the user might forget the answers. 

So, I guess we either assume the person who controls the email is the user, or we have N steps to try and authenticate them, then go to a admin) :(  Also, forcing people to use gpg is not at all good.

**Comment by StephenCoady** [comment]
As per the acceptance criteria created by @abompard above I've opened a PR. If there are strong feelings against the basic box containing email instructions and a viable alternative solution then I'm happy to change the PR.

**Comment by abompard** [comment]
@nirik We currently force people to have a GPG key if they want to use 2FA, do you think that's a bad idea?

**Comment by nirik** [comment]
Well, I guess it's tied to this? But yeah, I would prefer not to... IMHO gpg is something that only really geeky people are willing to put up with. :( 

Perhaps we can/should require two tokens? increasing the chance that if the user lost one they still have the other?

It's hard to see good alternatives on these cases... we either depend that the email address controller is the person, or we go through increasing piles of things we hope the real owner will remember. 
I guess punting to admins is the easiest we can do.

**Comment by abompard** [comment]
If we require two tokens I'm betting most users will just enroll 2 tokens in the same app on the same phone.

So, should we revert #155 and the GPG-related part of #147? Does anybody else have an opinion on that?
