### ISSUE TITLE
As a User who has enrolled a 2FA token, I want the forgot-my-password process to handle the situation securely

### ISSUE THREAD

**Issue by abompard** [fedora-infra/noggin#152]
We need to decide what happens in the forgot-my-password process when the user has 2FA. I see the following possibilities:

1. Remove all existing tokens when the password is reset
2. Stop the procedure and ask users to send a GPG-signed email to admins so that they remove their token before asking for a password reset on the portal
3. Ask for the token in addition to the new password and check it (but I'm not sure the FreeIPA API can do that)

Option 1 seems less secure, but would allow to reset a user's lost token. It would also allow anybody who has access to a user's mailbox to reset that user's passwords regardless of 2FA, so, that seems bad.

I wonder what you guys think of this situation and how we should handle it. @relrod, any idea?

**Comment by abompard** [comment]
Hey @puiterwijk  and @nirik , I'd love to have your opinion on what we should do in these cases too... Thanks!

**Comment by puiterwijk** [comment]
1 is out straight away.
Option 3 has my vast, VAST preference.
Option 2 is acceptable as a fallback if they no longer have access to their token.

**Comment by abompard** [comment]
OK, let's try to implement n°3. @tiran , do you know if the FreeIPA API allows us to just check a token, not the password+token combination?

**Comment by tiran** [comment]
The password change dialog also takes an OTP token value in addition to the old password and the new password. I *think* FreeIPA already enforces that you have to enter an OTP when password+OTP is configured as only auth method.

Note: You cannot remove the last OTP token when password+OTP is enabled.

**Comment by abompard** [comment]
Thanks @tiran , but here I'm considering a "forgot-my-password" procedure where the user doesn't know their current password.

**Comment by nirik** [comment]
I guess 3 would be best for me too. I think right now we assume if you control the email address you are the user (which is not really great). I'm not sure how better to handle this case however. We could store and ask for security questions/answers, but thats pretty complex. 
I'd really prefer to avoid manual handling and also gpg.
Could we somehow authenticate them with their ssh key(s)? 
Or perhaps we should look at what freeipa does here... ask for admin intervention?

**Comment by ryanlerch** [comment]
AFAICT, there is no way in IPA at the moment to check an OTP token in this way. when acutally changing the password, we are first using the admin user to force the change to the new password, then changing it again as the user to the same password (this is just to ensure it is not expired.)

https://github.com/fedora-infra/noggin/blob/066926428a387875dea94a1f33702aad19465117/noggin/controller/password.py#L186-L189

None of these methods allow supplying an OTP. the `passwd` api endpoint in the client legacy appears to, but not sure how we can make this work, with having to force the change as admin first.

**Comment by ryanlerch** [comment]
Also, the current workflow is this (if a user has an OTP token on their account):

1. User supplies username, and email is sent to their email address
2. They can use that to reset the password (and don't need to supply their OTP)
3. Because they have an otp token, they still need that and the password they just supplied to log in still.

as i see it here, the bad thing that can currently happen is a bad actor, that also has access to their email address, but not their OTP, can reset their password, but still not log in because they dont have the right OTP. So a potential DoS.

**Comment by abompard** [comment]
Implemented in #166 (5219783e)
