### ISSUE TITLE
As a User who has enrolled a 2FA token, I want to have to provide my token when I login to a web app through Ipsilon

### ISSUE THREAD

**Issue by abompard** [fedora-infra/noggin#154]
I think Ipsilon already supports that, but we need to test it.

**Acceptance Criteria**
- A user with an enrolled OTP token needs to provide it to Ipsilon.

**Definition of Done**
- All AC are met.

**Comment by Conan-Kudo** [comment]
As far as I can tell, Ipsilon does not support WebAuthn/FIDO/U2F for 2FA tokens (like YubiKey), and this will require a pull request to Ipsilon to add. For that matter, it doesn't seem anyone has this feature yet.

At least when such PR is made to add it, I can review it and merge it relatively quickly once I make sure it works (as I'm standing up this setup in openSUSE infrastructure too).

**Comment by abompard** [comment]
Yeah, FreeIPA does not support U2F yet (https://pagure.io/freeipa/issue/6632) so we can't have that. We're doing 2FA the old way, with digits.

**Comment by Conan-Kudo** [comment]
We still need a page and some wiring in Ipsilon for the legacy TOTP stuff, but it's worth planning for the WebAuthn future when designing that.

**Comment by StephenCoady** [comment]
I am having some trouble running ipsilon in our dev environment to test this. I've hit this issue: https://pagure.io/ipsilon/issue/322. I managed to get past it by not raising the error but the service is not running correctly and somehow manages to break the ipa-server as I lose access.

I will come back to this tomorrow with (hopefully) fresh eyes. If not, I will try to install it somewhere else instead.

**Comment by StephenCoady** [comment]
I managed to get this working - I had to install ipsilon on a separate box and point it at freeipa.

Can confirm that it works perfectly and if a user has otp tokens then providing them to ipsilon also logs them in.
