### ISSUE TITLE
Confusing Error message on bad first name entry

### ISSUE THREAD

**Issue by siddharthvipul** [fedora-infra/noggin#180]
Leaving a space in first name field gives: `invalid 'first': Leading and trailing spaces are not allowed`.
Would be better to say Invalid first name instead of just first.
Even better would be to trim the name and not having that error shown at all.

**Comment by abompard** [comment]
I can reproduce it. This message is returned by the FreeIPA server and not caught in the controller.
The way I see it, there are two things we can do about it:

1. in the controller, intercept more messages in the `ValidationError` handler and convert them to `FormError`s. We currently only handle the `login/username` field. We'll need a mapping from IPA field to form field, but thankfully the trailing space error makes it easy to test for.
2. in the form, strip field values that need to be stripped

I think both are useful to do, this way we'll be able to catch more unexpected server errors.

**Comment by abompard** [comment]
Fixed in #183
