### ISSUE TITLE
Change in profile settings is forgotten when tab is changed

### ISSUE THREAD

**Issue by Zlopez** [fedora-infra/noggin#182]
## Description
When doing change in Profile settings and moving to another tab without saving changes the change is forgotten.

## Steps to reproduce
1. Login
2. Open Settings
3. Change anything in Profile
4. Switch to OTP tab

## Expected output
Dialog to ask if I want to save the changes.

## Current output
Change is silently forgotten.

**Comment by abompard** [comment]
I suppose we could switch to javascript-based tabs, have all the forms on the same page and differentiate them with prefixes, like the login and register forms on the front page.

**Comment by ryanlerch** [comment]
Just out of interest, why do you expect the changes to be saved without pressing the button to submit the form?

Take for example the personal settings page here on GitHub. If you edit your name, then click another setting grouping without submitting that form, it just takes you to the new settings page. (no dialog, and changes arent saved.)

If you fill out a form (a non-ajaxy one), and change pages without submitting the form, it usually does what happens here.

Do we need to make the save changes button bigger?

@abompard not sure putting this back into one page will help. if you edit one without pressing submit, then switch to another, and edit it and press submit, it will only submit the one you press submit for, won't it?

**Comment by Zlopez** [comment]
I don't expect the changes to be silently saved. I expect to see dialog with something like: "You did some changes, do you want to save them?"

What I was complaining about is that the changes are just silently forgotten or silently saved. Which you don't know till you check the Settings again. Something like Schrodinger's cat :-)

**Comment by abompard** [comment]
> @abompard not sure putting this back into one page will help. if you edit one without pressing submit, then switch to another, and edit it and press submit, it will only submit the one you press submit for, won't it?

We would need to make one big form with all the settings in there and have the tab system be inside that big form. (you're right, form prefixes are not the solution here)
It would work, but it would make the form treatment server-side more complex. What do you think?
