### ISSUE TITLE
validate email before allowing account creation

### ISSUE THREAD

**Issue by nirik** [fedora-infra/noggin#184]
Right now you can fill in the account creation information and then login right after. 

But this means: 

* You can use whatever email you want, you could use someones email you don't like and start behaving poorly and give them a bad reputation. 
* You could be a spammer and just create 10,000 accounts with bogus email addresses. 

We should validate their email before allowing the account creation to finish. Send an email with a activation link or token or something. 

Feel free to close if this is already filed or addressed. Thanks!

**Comment by arrfab** [comment]
+1

**Comment by abompard** [comment]
Hmm, we need to find a way to store pending validation email addresses if we want to do that.
Does the current FAS validate emails?

**Comment by arrfab** [comment]
Yes it does, and only permits you to have valid account and change initial password after email validation.

**Comment by abompard** [comment]
We'll probably switch to using `stageuser`s to register users and activate them when their email is verified, see fedora-infra/freeipa-fas#86 for other details and documentation

**Comment by abompard** [comment]
OK, this should be ready for review now, there's only one failing test and it should be fixed by fedora-infra/freeipa-fas#89.
