### ISSUE TITLE
profile vs settings

### ISSUE THREAD

**Issue by nirik** [fedora-infra/noggin#186]
There is both 'profile' and 'settings' in the user pull down, and they do go to slightly different places, but are they different much? should it just be one or the other everywhere?

**Comment by abompard** [comment]
@ryanlerch , do you have an opinion on that?

**Comment by mohanboddu** [comment]
I guess removing `Settings` from drop down is easier and makes it less confusing. People can always go to profile and make the changes as part of settings.
