### ISSUE TITLE
Allow for multiple irc nicks

### ISSUE THREAD

**Issue by nirik** [fedora-infra/noggin#187]
Some people have multiple irc nicks. Might be nice to allow a list there. Possibly : seperated?

**Comment by abompard** [comment]
What do you mean by "separated"?

**Comment by ryanlerch** [comment]
@nirik did you mean comma separated?

**Comment by ryanlerch** [comment]
**Acceptance Criteria**
* user can add or remove multiple IRC nicknames in the noggin interface
* freeipa-fas is updated to allow multiple nicknames
* the user profile page displays all of the IRC nicknames the user has defined.

**Definition of Done**
* All of the above works
* Unit tests with 100% coverage
* CI passes

**Comment by nirik** [comment]
> @nirik did you mean comma separated?

Yes, sorry. :)
