### ISSUE TITLE
Disallow leaving 'ipausers' or other critical groups

### ISSUE THREAD

**Issue by nirik** [fedora-infra/noggin#189]
Currently I can leave the default 'ipausers' group, is that expected?

There might be other automated groups we want to not allow people to leave too.

**Comment by arrfab** [comment]
+1 and I'd even say that this particular group from IPA would have to be hidden through noggin (imho)

**Comment by StephenCoady** [comment]
I'm going to take a look at this, but specifically for `ipausers` at the moment. If we find there are others then I can repeat the process for those too.

**Comment by arrfab** [comment]
Wondering if that's not even easier to just have a config with a simple list that would be parsed and automatically "hidden" through noggin.
On FAS, we had $random_people trying to join system groups so just hiding those from WebUI (but still used in the background directly in IPA) would probably make sense ?

**Comment by abompard** [comment]
Yep, just use a list in `noggin/defaults.cfg`
