### ISSUE TITLE
API documentation is missing

### ISSUE THREAD

**Issue by mohanboddu** [fedora-infra/noggin#193]
API documentation is missing in https://noggin-aaa.readthedocs.io/en/latest/api.html

**Comment by ryanlerch** [comment]
@abompard noggin won't have an API, right? Should we remove this stub from the docs, and move it to fasjson? (and also move this issue over too)

**Comment by ryanlerch** [comment]
Okies, it looks like there is an issue for API Docs for FASJson already:

https://github.com/fedora-infra/fasjson/issues/30

So IMHO, all that needs to be done here is:

**Acceptance Criteria**
* Documentation for Noggin does not have a stub where the API Docs should appear to go
* Documentation for Noggin refers to the FasJSON documentation for details on the API

**DoD**
The above is done
