### ISSUE TITLE
As a user I want to be able to enable a token I have previously disabled so that I can use it again

### ISSUE THREAD

**Issue by mohanboddu** [fedora-infra/noggin#194]
We should allow users to re-enable an OTP token they have previously disabled. The `otptoken_mod` already exists in `ipa.py` so we will just need to add the button to the view and test it.

_Original question: Is there any way to activate a disabled token? If not, why keep them after disabling and how it will be different from deleting the token?_

**Comment by abompard** [comment]
@ryanlerch & @StephenCoady , you worked on that part I think, could you answer?

**Comment by StephenCoady** [comment]
@mohanboddu yeah good point, it is possible to enable a token once it has been disabled.

@abompard we already have the function to do this so it would be just testing and a bit of front end. I can create the ticket.

edit: just thinking I can update the title and description of this one instead.

**Comment by abompard** [comment]
Thanks!
