### ISSUE TITLE
(S) Wireframe the browse / search / list groups page

### ISSUE THREAD

**Issue by sfinn85** [fedora-infra/noggin#2]

**Comment by sfinn85** [comment]
**Acceptance Criteria:**

Visual wire frame of new user form
Fields ( TBC )
Working doc

**DOD:**
All above completed

**Comment by ryanlerch** [comment]
first pass at the browse / list / search pages for users and groups

![userlist](https://user-images.githubusercontent.com/592259/71964957-70d1fc80-324a-11ea-97f3-48a3645fb007.png)
![grouplist](https://user-images.githubusercontent.com/592259/71964959-70d1fc80-324a-11ea-9404-9cea5fedbe4c.png)

**Comment by StephenCoady** [comment]
Looks good to me.

**Comment by sfinn85** [comment]
Yep looks good to me. 

 Few points

- The list is quite long on one page, is this the norm for these accounts, or do we just have a search bar instead of listing all the groups/ users? 
- If we need to list could be reduce the number shown on each page and have them in alphabetical order?
- Has anything changed in design from current design that we would need to review from dev perspective?  

Thoughts..

**Comment by ryanlerch** [comment]
Therotically, we would want this paginated, but not sure if the ipa backend makes this possible or easy, so didnt put it in the wireframe for now.

**Comment by sfinn85** [comment]
Cool, thanks @ryanlerch .

@relrod what are your thoughts here? If we can improve UX as we build AAA excellent but only if we have the capacity to do so.

**Comment by sfinn85** [comment]
Possible solutions from Rick - to discuss.  ( UI to be tweaked)

**Comment by relrod** [comment]
@ryanlerch Would paginating client-side instead work?

**Comment by ryanlerch** [comment]
@relrod works for me, but only if we are talking loading clientside with ajax. otherwise better to just show all the entries here. It is kind of useless to load all the items in the html, then artificially paginate clientside imho.

**Comment by relrod** [comment]
@ryanlerch fair. I don't know if the IPA API handles pagination (I can look in a bit). I figured just not dumping everything on the page could look nice from a UX perspective, even if we pull all the results at once. But I'm fine with whatever :)

**Comment by sfinn85** [comment]
leave wireframe as is, lots of work to change, search functionality available to refine user view
