### ISSUE TITLE
As an application owner, I want a fedora-messaging message to be emitted when some user data are changed

### ISSUE THREAD

**Issue by mscherer** [fedora-infra/noggin#209]
We need the noggin to emit a message when a user change their ssh key, timezone, gpg key or password to emit a message, because the Badges application uses it. FAS used to emit a message on the fas.user.update topic, the contents could be modelled after it (or adapted).

**Acceptance Criteria**:
* a Fedora Messaging message is emitted when a user is updated
* to ease transition and if it's possible, the message should be emitted on the same topic with the same content.
* a crash in the message sending code should cause a message to be logged with full traceback, but the page should not fail rendering.

**Definition of Done**:
* all the above is done
* unit tests for 100% coverage (unless explicitely ignored with an explanation)
* CI passes
* the path to the Fedora Messaging configuration can be set by a configuration variable.
* the message should use schemas
* there is documentation on the message schema and its contents

**Comment by abompard** [comment]
There is controversy around publishing a public message when a users changes their password (see https://github.com/fedora-infra/noggin/issues/25#issuecomment-582961135). Can the applications do without that notification?

**Comment by mscherer** [comment]
No, we give badge based on that precise event:
https://badges.fedoraproject.org/badge/paranoid-panda

I would even say that we could use badge as a incentive to change password on a regular basis, which could be a good idea too (even if mandatory rotation is not great)

I would also add that seeing that a password was changed could also tell something fishy did happen. Like if I know that a admin X is in vacation, but there is a password change, maybe there is something fishy.

And as indicated in the other ticket, I think a clearer rational than "I hate this" could be provided, as there isn't much discussion to have on that fact.

**Comment by abompard** [comment]
@relrod , what do you think of this?

**Comment by relrod** [comment]
Password changes should pretty clearly not be a public event. Consider a scenario where someone with a high level of access is being targeted. Broadcasting this information tells the attacker "restart your search" which is information we need to not leak.

There's a reason this information is kept in shadow and not passwd on Linux systems and why reading the journal (where password changes are logged) requires elevated privileges.

```
[codeblock@batcave01 ~][PROD]$ chage -l root
chage: Permission denied.
```

**Comment by mscherer** [comment]
I disagree on the reasoning.

First, the information is stored in /etc/shadow because there is no way to modify 2 files in a atomic way using UNIX primitives. So if you want to change the hash and the last time it was changed and avoid race conditions, it has to be done in 1 single edit on 1 single file. The information is not stored in shadow because this is seen as sensitive, but because we do not have choice. 

LDAP, being a proper database with a ACL system, do not have that limitation, and this is not uncommon to see directories without restriction on shadowLastChange.

For example, this seems to be the example config on several documentations:
https://wiki.gentoo.org/wiki/Centralized_authentication_using_OpenLDAP#Access_management_.28ACLs.29
https://wiki.archlinux.org/index.php/LDAP_authentication#Set_up_access_controls
https://help.ubuntu.com/lts/serverguide/openldap-server.html

So I disagree with the assumption "it should pretty clearly not be a public event", given the reason for it not being public seems more related to UNIX limitation, and there is examples where this isn't. There is clearly foks who think like you, I do not deny, but it doesn't seems to be as clearcut as you say.

For the point about journal, I disagree too. There isn't even the concept of "public event" on UNIX and things either go to system journal (that only root/adm can read) or user journal (that only user and root can read). No matter where the log go, it would not be public and would requires elevated privileges to be read. And not because this is sensitive, but because there is again no choice anyway. So deducing sensitivity based on where the information is logged is a stretch IMHO.

In the end, the whole point is "chage do have that policy hardcoded, so we should too", which is not a very strong argument.
 
As someone who also did successfully found a way to get root access on Fedora most sensitive server (my flock talk in 2018), I would also point that attacking password is in no way practical. We do have systems to prevent bruteforce (or so do I hope), we do have 2FA, and restarting bruteforce wouldn't even come to my mind, due to the probability of people changing it just during the attack being quite low. If the change is related to the attack, I do hope that the attacker would be blocked, so the message say nothing. And if the change is unrelated, that just mean that we were lucky that the old password wasn't found sooner, and luck is not really a security system.

Now, to go back on reason we might to emit that event, there is also the use for session invalidation. If a attacker successfully get a password (like a password reuse from a leak, not really uncommon), and get logged on a system (like pagure), changing password wouldn't be sufficient to kick them out. having a password change message triggering sessions invalidation would be a way to mitigate the effect of such attack.

So we have one 1 hand:
* "it help a attacker who would restart bruteforce", which I think would be pretty uncommon 
* "we always have done this way since the 90s"

On the other hand, we would:
* "unbreak badges" (we already have a few people complaining about that)
* "mitigate successful attack with session cleaning" (with password reuse being much more common than password bruteforcing)
* "signal something is weird to the target" (since I would immediately react if I get a notification on fmn "someone changed your password"

So I rest my case.
