### ISSUE TITLE
As a user, i want to view a list of groups that i belong to, to easily mananage my group memberships

### ISSUE THREAD

**Issue by sfinn85** [fedora-infra/noggin#21]

**Comment by ryanlerch** [comment]
The user detail page currently lists group memberships. so IMHO this one is already done

**Comment by abompard** [comment]
Is does not seem possible to remove oneself from a group when one is not a group sponsor. I think it should be possible, and it definitely is in current FAS

I think it is implied by "manage my group memberships", but maybe we should change the title? Or create a new User Story?

**Comment by abompard** [comment]
I've created a new User Story: #108
