### ISSUE TITLE
Confirmation while adding new users or removing users from a group

### ISSUE THREAD

**Issue by mohanboddu** [fedora-infra/noggin#211]
While adding new users to a group or removing existing users from a group, it would be nice to give a dialog/popup confirming the change.

**Comment by ryanlerch** [comment]
Just out of interest, what is the rationale for adding an extra step here?

At the moment, when you add or remove a member from a group, it gives you a notification telling you that "user has been removed".

Not sure we want to add an extra step here for a 5% edge case of accidentally adding or removing a user, when (if done by accident), adding or removing that user is a pretty trivial step to undo.

**Comment by mohanboddu** [comment]
I agree, but I am worried that in those 5% of accidental changes, what if people wouldn't pay attention to the notification.

**Comment by ryanlerch** [comment]
I still think adding an extra step here for the edge case is too much.

how about something like an "undo" link in the flash notification. this way if it is done in error, it can more easily be reverted.

**Comment by mohanboddu** [comment]
Sure, that works too.

**Comment by abompard** [comment]
**Acceptance criteria**

- The flash message confirming addition or removal to/from a group should contain an "Undo" button
- This button will remove the user that was just added or add the user that was just removed via the proper POST request

**Definition of Done**
- All CI tests pass
- The button is appropriately styled
