### ISSUE TITLE
Not showing all groups that I am part of under "Groups" tab in profile page

### ISSUE THREAD

**Issue by mohanboddu** [fedora-infra/noggin#212]
I am a member of `ipausers` group and a sponsor of `mohans-group` but in the profile page under groups, I am only seeing `ipausers` group but not the `mohans-group` group.

**Comment by abompard** [comment]
I'm guessing that's because you're a *sponsor* of `mohans-group` but not a *member* of it.

**Comment by mohanboddu** [comment]
> I'm guessing that's because you're a _sponsor_ of `mohans-group` but not a _member_ of it.

Sure, but wouldn't it be nice to show that as well, since in the groups list, it shows `member` next to `ipausers` group, just like that it can show `sponsor` next to `mohans-group`

**Comment by ryanlerch** [comment]
**Acceptance Criteria**
* on the user profile page's groups listing, the list of groups a user is linked too is updated so each group shows 1 or 2 associations.
** if a user is both a sponsor and a member: show sponsor and member labels. 
** if a user is only a member, only show a member label.
** if a user is only a sponsor, only show a sponsor label 

**Definition of Done**
* All of the above works
* Unit tests are written to check the three cases above.
* Unit tests with 100% coverage
* CI passes
