### ISSUE TITLE
Dont show "To join this group, contact a group sponsor." if the user is a sponsor

### ISSUE THREAD

**Issue by mohanboddu** [fedora-infra/noggin#215]
As a sponsor of a group, I am already part of the group, so I don't want to see `To join this group, contact a group sponsor.` as it seems redundant.

**Comment by abompard** [comment]
Actually, being a group sponsor does not make you automatically a member of the group. The message is indeed useless though, because you don't need to contact yourself ;-)

**Comment by mohanboddu** [comment]
> Actually, being a group sponsor does not make you automatically a member of the group. 

What is the difference then (other than able to sponsor someone)? Cant a sponsor get all the permissions as that of a member?
