### ISSUE TITLE
Noggin dependency check for packaging (Fedora, EPEL, openSUSE Leap)

### ISSUE THREAD

**Issue by Conan-Kudo** [fedora-infra/noggin#227]
I'm trying to package noggin for Fedora, EPEL 8, and openSUSE Leap 15.2, but it seems like this is going to be somewhat difficult...

I took a look at the dependency list and then made a chart about what's available:

|                  | Poetry/PyPI | CentOS 8 | Fedora 31 | Fedora 32 | openSUSE Leap 15.2 |
|:----------------:|-------------|----------|-----------|-----------|--------------------|
| python3          | ^3.6        | 3.6      | 3.7       | 3.8       | 3.6                |
| cryptography     | ^2.9        | 2.3      | 2.6.1     | 2.8       | 2.8                |
| flask            | ^1.1        | 0.12.2   | 1.0.2     | 1.1.1     | 1.0.2              |
| flask-wtf        | ^0.14       | 0.14.2   | 0.14.2    | 0.14.2    | 0.14.2             |
| python-freeipa   | 1.0.0       | 1.0.2    | 1.0.2     | 1.0.2     | 1.0.2              |
| click            | ^7.0        | 6.7      | 7.0       | 7.0       | 7.0                |
| pyjwt            | ^1.7.1      | 1.6.1    | 1.7.1     | 1.7.1     | 1.7.1              |
| flask-mail       | ^0.9.1      |          | 0.9.1     | 0.9.1     | 0.9.1              |
| gunicorn         | ^20.0       |          | 19.9.0    | 20.0.4    | 19.7.1             |
| fedora-messaging | ^2.0.1      | 1.7.1    | 2.0.1     | 2.0.1     |                    |
| backoff          | ^1.10.0     | 1.6.0    | 1.6.0     | 1.6.0     | 1.10.0             |
| noggin-messages  | git         |          |           |           |                    |
| whitenoise       | ^5.0.1      |          | 4.1.4     | 5.0.1     | 4.1.3              |
| flask-babel      | ^1.0.0      |          | 0.11.2    | 0.11.2    | 0.12.2             |

It seems like right out of the gate, we can't package it anywhere. Would it be possible to make it so Noggin can be packaged on at least Fedora 31+ and openSUSE Leap 15.2?

**Comment by Conan-Kudo** [comment]
By the way, the reason I'm filing this is that in openSUSE, we're planning on initially deploying this on a Fedora 31 VM and then later in the year transitioning to openSUSE Leap 15.2.

**Comment by abompard** [comment]
Hey, thanks for the table. Are you planning on deploying it using RPMs only? The only packages with semver incompatibilities are:
- whitenoise: we use it very little and I would be surprised if we were using a new API
- flask-babel: yeah that's a big bump and someone should check the compatibility with the previous versions, however we only use a couple APIs
- gunicorn: I don't think this should be a problem and we only use it for deployment, you can run the app on something else if you want to (it's not a hard dependency)

For the rest, we would need to check if we are using new APIs, but it should be rare and we can consider not using those APIs on a case-by-base basis, if not using them is not too much of a dev+maintenance burden. Could you try just running noggin on F31 with existing libraries and check if it works?

**Comment by Conan-Kudo** [comment]
Yes, we are planning on deploying via RPMs only.

I can certainly start giving it a shot and see how it goes.

**Comment by Conan-Kudo** [comment]
Good news with flask-babel, it seems like bumping to 1.0.0 is largely backwards compatible (so [I sent a PR to do so](https://src.fedoraproject.org/rpms/python-flask-babel/pull-request/5)), but in 1.0.0, they introduced support for lazily evaluated gettext strings and fixed locale selection in multi-threaded Flask apps.

**Comment by Conan-Kudo** [comment]
I've built packages for testing in the [`ngompa/fedora-aaa`](https://copr.fedorainfracloud.org/coprs/ngompa/fedora-aaa/) COPR for Fedora 31 and higher.

The [sources for the packaging](https://pagure.io/fedora-aaa-copr-packaging) is open to issues and PRs based on what people tell me about how well they (don't) work. 😉
