### ISSUE TITLE
blacklisting some domains when registering account (to avoid loop with aliases)

### ISSUE THREAD

**Issue by arrfab** [fedora-infra/noggin#234]
In the actual deployed instance, noggin let you register with any email address (there is another ticket open for validation)
Problem is that it doesn't refuse some domains, including @fedoraproject.org .
But because email aliases are generated from FAS/IPA, users shouldn't be able to register with such alias (generated *from* IPA), as that would cause a loop (even for password reset instructions, etc)

**Comment by ryanlerch** [comment]
@tiran @abompard is making this blacklist something that we should (if we can) do in freeipa-fas? or just implement it in noggin?

**Comment by arrfab** [comment]
Hi, so we have someone who recently updated his email address through noggin with his new @centosproject.org alias, meaning that "blocklist" wasn't implemented, creating a loop : his alias for centosproject.org was so automatically redirecting to same address for postfix virtusertable.

Can we ensure that `centosproject.org` is so added to the blocklist to ensure that nobody can register/update with such email address ?

**Comment by abompard** [comment]
That was a configuration issue, closing.
