### ISSUE TITLE
Can't start the application with gunicorn and uwsgi

### ISSUE THREAD

**Issue by hellcp** [fedora-infra/noggin#249]
Whatever I tried, starting noggin with gunicorn or uwsgi results in the following page:

---
<h1>Not Found</h1>
<p>The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.</p>

---

And using flask's built in webserver doesn't seem like too great of an idea for deployments

**Comment by Conan-Kudo** [comment]
This should be fixed now with https://pagure.io/fedora-aaa-copr-packaging/c/c7fff335612150875336be8ef63749ed6bdae00e
