### ISSUE TITLE
fedora-messaging integration

### ISSUE THREAD

**Issue by sfinn85** [fedora-infra/noggin#25]

**Comment by abompard** [comment]
We could look at what messages are currently emitted by FAS and tweak IPA to emit them when similar events occur. But is there anybody consuming those messages? Is this requirement coming from someone in particular? In our Ansible infra repo I don't see any app subscribed to these messages.

**Comment by relrod** [comment]
Copying from my comment from the original internal jira ticket:

*    `fas.group.create` - I can't think of anything that needs to act on this. Also this won't be done by the portal, it'll be done by admins using IPA commands.
*    `fas.group.member.apply` - we aren't allowing users to apply to groups anymore, so this doesn't apply (no pun intended)
*    `fas.group.member.remove` - not sure we need to act on this
*    `fas.group.member.sponsor` - **Used by badges, so we might need this one**
*    `fas.group.update` - again only done by admins now, using IPA commands
*    `fas.role.update` - no longer applies
*    `fas.user.create` - **Used by badges so we might need this one**
*    `fas.user.update` - Please NO. I hate that password change notifications were EVER sent over fedmsg. No.

**Comment by abompard** [comment]
Thanks Rick! Do you think that this should be emitted by the portal? It feels like FreeIPA is the place where messages should be emitted from, but I haven't found an easy way to plug into whatever events happen inside (except maybe [callbacks](https://abbra.fedorapeople.org/freeipa-extensibility.html#sec-5) but that does not seem simple).
If it's impossible or too hard, I guess securitas can emit those messages.

**Comment by relrod** [comment]
Yes, it should be on the securitas side

**Comment by sfinn85** [comment]
Opp for pair programming if we have time

**Comment by abompard** [comment]
This has been split off into #140 and #141. Removing from the board.

**Comment by ryanlerch** [comment]
> This has been split off into #140 and #141. Removing from the board.

these have both been implemented. closing this one off

**Comment by mscherer** [comment]
For the record, badge also use fas.user.update for ssh keys and timezone (see crypto-bager). I guess that a better rational that "I hate this" could be given.

**Comment by abompard** [comment]
Password change is a different operation than profile change in noggin, so I guess we could send a message on profile update and not on password change. Would that work for you @relrod ?
