### ISSUE TITLE
As an appropriately privileged user, I want to be able to override and set email aliases for myself

### ISSUE THREAD

**Issue by Conan-Kudo** [fedora-infra/noggin#257]
In openSUSE, our legacy system (openSUSE Connect) gives administrators the ability to modify the default alias for a user account to another name, provided it's not taken by another account. Additionally, administrators can provision additional aliases for users upon request. Also, appropriately privileged users can do this to their own user accounts.

This is a feature we need to have with this system eventually.~~, though making this self-service is also something that would be interesting to explore (if possible).~~

EDIT: After further discussion with @hellcp and @abompard, I'm revising this to reflect what the actual functionality is (and asked for) and what we discussed in our call about this.

**Comment by abompard** [comment]
Hmm I guess this would be done directly in FreeIPA, no? There are mailserver-oriented objectclasses that can store email aliases for users and the mailserver can be configured to look into LDAP for aliases, so I don't think this involves Noggin in any way.

**Comment by Conan-Kudo** [comment]
@abompard Maybe? I think part of the idea here was that if noggin has an admin view for user management, we probably want this to be handled there. Admittedly, I haven't looked to see if FreeIPA web administration offers this capability.

(cc: @hellcp)

**Comment by Conan-Kudo** [comment]
@abompard @hellcp @ryanlerch I've revised this RFE user story to match what we discussed. This is not an _immediate_ need, but is something we should figure out in the future.
