### ISSUE TITLE
continue internationalization?

### ISSUE THREAD

**Issue by Jibec** [fedora-infra/noggin#261]
hello, may I continue internationalization?

this PR looks huge: https://github.com/fedora-infra/noggin/pull/200 and I'm afraid to create many conflicts. Or should I proceed?

when should this application be deployed? I see no milestone: https://github.com/fedora-infra/noggin/milestones
where is the good place to talk with your team to ask such questions?

**Comment by ryanlerch** [comment]
Little unsure about this one. What is left to do on the i18n side? 

AFAIK, all the strings are marked up, and the appropriate language is shown to the user.

If there are missing pieces here, it might be worth splitting them up into separate issues? One thing we could do here is use the "locale" setting in the user profile to ovcerride the langugage that is presented to the user, but other than that, not sure what else there is to do (other than the localization of course)

**Comment by Jibec** [comment]
Le 07/05/2020 à 01:38, Ryan Lerch a écrit :
> Little unsure about this one. What is left to do on the i18n side?

Oh, great, I didn't the check the resulting pot file.

I can plug the translation platform and allow translators to come and
contribute.
Can I do it right away?

-- 
Jean-Baptiste Holcroft

**Comment by abompard** [comment]
Sure, thanks

**Comment by Jibec** [comment]
Done: https://translate.fedoraproject.org/projects/fedora-infra/noggin/

I'm far for personal computer, could you please add this widget to the 
readme? 
https://translate.fedoraproject.org/widgets/fedora-infra/?component=noggin#287x66
(or any other of your choice)

**Comment by Jibec** [comment]
Notes:

Weblate will automatically update po files to match pot file. To prevent 
conflicts, please don't change any po files.

Weblate will open a Pull Request, you don't have to merge the PR each 
time to get it, Weblate will reuse it for new contributions (and squash 
commits per author to reduce the volumes).
Merge it every once in a while.

I tried the feature to remote line numbers in po files. I don't think it 
has any other impact but reducing commit diff size. I'll change it if it 
happen to create issues.
