### ISSUE TITLE
As an AAA administrator, I want to disable accounts, so that the bad person no longer has access to our systems.

### ISSUE THREAD

**Issue by sfinn85** [fedora-infra/noggin#28]

**Comment by ryanlerch** [comment]
This one may be out of scope for securitas? Disabling of an account (i assume) is already possible with freeIPA web application or command line tools.

**Comment by StephenCoady** [comment]
@ryanlerch agreed it is possible in freeipa so this should be closed.

**Comment by sfinn85** [comment]
Closing as this is currently in place. 

Thanks all
