### ISSUE TITLE
(s) Wireframe the group detail page. 

### ISSUE THREAD

**Issue by sfinn85** [fedora-infra/noggin#3]

**Comment by sfinn85** [comment]
This is the page that a user views the details of a specific group, as well as request membership to a group. Group owners will have further permissions to manage group membership on this page. Note: 

Acceptance Criteria:

Visual wire frame of new user form
Fields ( TBC )

Working doc
**DOD:**
All above completed

**Comment by ryanlerch** [comment]
First pass at the group detail page

![grouppage](https://user-images.githubusercontent.com/592259/71964800-22bcf900-324a-11ea-9b88-e92352ece29a.png)

**Comment by StephenCoady** [comment]
Looks good, nothing to add except maybe we could filter by user name for larger groups.

**Comment by sfinn85** [comment]
Looks good to me,  the team are more equipped with providing feedback on what is needed or will improve experience from a user perspective, so I would take Stephen's feedback on board. I would also be mindful too, if we do add filter by user name for larger groups, is this creating more dev work in the backend, if so , we need to ensure it's worth doing before proceeding.

@relrod can you provide some insight here?  Thanks all

**Comment by ryanlerch** [comment]
![grouppage](https://user-images.githubusercontent.com/592259/72424505-dafe1a80-37d1-11ea-9d6b-2f5e19ee74cb.png)

**Comment by StephenCoady** [comment]
Looks great!

**Comment by sfinn85** [comment]
Looks good @ryanlerch. @StephenCoady  Search seems to be a  new addition for this build,  or maybe we have search enabled on the current system just not here. Does it create more dev work?   
If so, how much? S/M/L or unknown

**Comment by StephenCoady** [comment]
@sfinn85 I think the search is an existing function as part of a different user story just being called here, so small I would say.
