### ISSUE TITLE
As an AAA administrator, I want to create a new group, so that the person who requested it is happy.

### ISSUE THREAD

**Issue by sfinn85** [fedora-infra/noggin#30]

**Comment by ryanlerch** [comment]
AFAICT, this is not within the scope of securitas, but will (can currently can) be done via the freeIPA web ui. So IMHO, this one is done.

**Comment by sfinn85** [comment]
Ok cool ,lets close thanks @ryanlerch

**Comment by sfinn85** [comment]
Can someone give me access to pull this into a project

**Comment by abompard** [comment]
@sfinn85 You don't see the "Projects" header on the right column? With a cog on the top right of the widget? If you see it then you can use it to add it to the AAA project, and then you'll be able to set the column from this same widget.
