### ISSUE TITLE
Don't use example.com for testing

### ISSUE THREAD

**Issue by abompard** [fedora-infra/noggin#304]
According to @tiran we should not be using `example.com` as a domain for testing. Using existing domains can lead to hard to debug issues. He recommends we switch to a TLD that does not exist, for example `noggin.test`.

**Comment by ryanlerch** [comment]
@tiran @abompard FWIW, i set it up this way primarily because this doc suggested it:

https://www.freeipa.org/page/Quick_Start_Guide

**Comment by tiran** [comment]
Oh thanks! I have updated the wikipage.
