### ISSUE TITLE
As a community group admin, I want to indicate my group's Matrix room ID for Matrix users to join

### ISSUE THREAD

**Issue by Conan-Kudo** [fedora-infra/noggin#309]
This is really the community group variant of #248.  In the same vein that we have for IRC channels, there's a need to be able to indicate Matrix room IDs.

Per [the Matrix specification](https://matrix.org/docs/spec/#users), the room ID format is `#room:server`. The [full specification of the identifier format](https://matrix.org/docs/spec/appendices#identifier-grammar) should probably be implemented to validate whether an entered Matrix room ID is valid or not and to support the proper uniqueness constraints.

This is a requirement for openSUSE, as we've stood up a Matrix server and "rehomed" all community channels on it. Consequently, primacy has moved from IRC to the Matrix, and we need a way to map group room presence in the Matrix in the same way Fedora does with IRC.

This will also be useful for Fedora, as Matrix-only rooms for Fedora are starting to exist, and having the ability to set and surface this to users will allow them the ability to join from a Matrix client easily.

**Comment by mattdm** [comment]
Is the auth server really the best place for this? Wouldn't groups just list these in https://docs.fedoraproject.org/en-US/engineering/ or https://docs.fedoraproject.org/en-US/mindshare/? What's the advantage of having it directly in the account system?

**Comment by Conan-Kudo** [comment]
The main advantage is that it's a machine-parseable authoritative reference of where to communicate with the "group" as it were. If a group has a channel of communication, having that information encoded in the group data makes it easy for people to reach out to them.

**Comment by mattdm** [comment]
Hmmm. There's a lot of general metadata for Fedora groups:

1. chat channel
2. mailing list or discourse category
3. docs
4. membership policies
5. ticket tracker
6. kanban board
7. currently active?
8. social media handles

... off the top of my head. There's probably more.

I agree it's nice to have that somewhere. If that somewhere is the account system, fine with me. What I don't want is yet another place for _some_ bits of this information.

**Comment by Conan-Kudo** [comment]
I think in lieu of building _yet another system_, we can leverage the fact that the AAA system is built on a _directory server_ which actually is designed to contain this information. We just need the fields for it.
