### ISSUE TITLE
As a registered user, I want my email alias to work, so that I look fancy with a @fedoraproject.org address.

### ISSUE THREAD

**Issue by sfinn85** [fedora-infra/noggin#31]

**Comment by abompard** [comment]
This seems out of scope for securitas. Is there something we should do @relrod ?

**Comment by ryanlerch** [comment]
@relrod any ideas on this one?

**Comment by relrod** [comment]
So I'm actually not 100% sure of the way forward on this one. It's in scope because right now fasclient is what generates the aliases. @puiterwijk

**Comment by markobrien1** [comment]
Initial implementation done and further bug fixes being tracked at https://pagure.io/fedora-infrastructure/issue/9854
