### ISSUE TITLE
Security Audit of Noggin Code Complete

### ISSUE THREAD

**Issue by amoloney1** [fedora-infra/noggin#316]
The code for Noggin needs to be audited for potential security risks and passed before deployment to staging.
* Add security headers https://github.com/fedora-infra/noggin/issues/333
    * Add justification lines to https://github.com/fedora-infra/noggin/issues/335
    * Review default config https://github.com/fedora-infra/noggin/issues/334
Move [installation docs](https://docs.google.com/document/d/1Ul2tmRWE9uV6hq96Z5uX3d12zjTFvkOjBjGVaL7KAiY/edit#heading=h.ik0gopv4v4lf) from gdoc to readthedocs 

Acceptance Criteria:
- The code is audited by a security personnel from Fedora
- Any security issues with the code are found, reported to the Noggin team using a Security Audit label and then are fixed
- The code passes all security reviews and signed off on

Definition of Done:
- [ ] Code passes security checks
- [ ] Installation Docs available
- [ ] Security headers updates
- [ ] Config notes reviewed

@puiterwijk Can you please action this request? Thank you kindly!

**Comment by puiterwijk** [comment]
I will try to schedule this soon, is there any deadline when this is wanted?
Additionally, how much flux can/should I still expect of the code, since a security audit is mostly useful after at least the security-sensitive code has stabilized somewhat.

**Comment by abompard** [comment]
The only big change in the code that is incoming is us using the non-legacy API of `python_freeipa`. That's going to change a lot of lines in a lot of files but it should end up in the exact same operations with FreeIPA, so I don't think it'll change much from a security point of view.
Apart from that, the code should be mostly done.

**Comment by amoloney1** [comment]
Hi @puiterwijk would you have an estimate date on when you will be able to complete the security audit please? The team are hoping to deploy Noggin in Staging by Aug 10th so if we could get the code reviewed before then, time willing of course, that would be great!
And thanks @abompard for adding more information to this ticket also! :)

**Comment by puiterwijk** [comment]
For reference, the commit hashes currently under audit:
- noggin: [0e3be29de02a1ba7aaf247493c5adf7d08e5f64b](https://github.com/fedora-infra/noggin/commit/0e3be29de02a1ba7aaf247493c5adf7d08e5f64b)
- freeipa-fas: [b0fc093b73c76bf100151a1a7d86d6171bfe7006](https://github.com/fedora-infra/freeipa-fas/commit/b0fc093b73c76bf100151a1a7d86d6171bfe7006)
- fasjson: [bb4a12ee9d949c40e69849dd4f38394c365f6dbb](https://github.com/fedora-infra/fasjson/commit/bb4a12ee9d949c40e69849dd4f38394c365f6dbb)

**Comment by puiterwijk** [comment]
According to the [Fedora Infrastructure Application Security Policy](https://docs.pagure.org/infra-docs/dev-guide/security_policy.html#audit), any deviations from the policy must be pointed out in the request for the security audit.
I cannot find any notes in this ticket to that extend, so I'm now adding that here:

The violated sections of the Application Security Policy and their justifications:
- [`Authentication`](https://docs.pagure.org/infra-docs/dev-guide/security_policy.html#authentication): noggin requires a token for direct access to IPA, and this is not possible with OpenID Connect. Additionally, there is no API in noggin.
- [`Authorization`](https://docs.pagure.org/infra-docs/dev-guide/security_policy.html#authorization): noggin doesn't use OpenID Connect per the previous justification

These justifications have been accepted as part of the security audit, so these sections will not apply to noggin for the purpose of this audit.
