### ISSUE TITLE
[secaudit-blocking] Missing security headers

### ISSUE THREAD

**Issue by puiterwijk** [fedora-infra/noggin#333]
Part of secaudit #316, blocking.

There are multiple security headers missing that are required per the [Fedora Infrastructure Application Security Policy](https://docs.pagure.org/infra-docs/dev-guide/security_policy.html#security-headers).

After logging in, the profile page is missing:
- [ ] `X-Frame-Options`: missing, `MUST`
- [ ] `X-Xss-Protection`: missing, `MUST`
- [ ] `X-Content-Type-Options`: missing, `MUST`
- [ ] `Referrer-Policy`: missing, `MUST`
- [ ] `Content-Security-Policy`, missing `MUST`

**Comment by abompard** [comment]
I'm working through this, setting the CSP header is causing some breakage that I'm trying to fix. I'm currently trying to find a workaround for this bug: https://github.com/twbs/bootstrap/issues/25394. The story is that Bootstrap use `data:image/svg+xml` in their CSS to draw arrows and such in forms, and allowing `data:` sources in the CSP [is insecure](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/img-src) (look for `data:`).
Not sure how practical it would be to extract all those images from the CSS and store them as files in the static dir. It seems like it'll be a maintenance burden, too.
