### ISSUE TITLE
[secaudit-blocking] Default configuration insecure defaults

### ISSUE THREAD

**Issue by puiterwijk** [fedora-infra/noggin#334]
Part of secaudit #316, blocking.

The default configuration, at [/noggin.cfg.default](https://github.com/fedora-infra/noggin/blob/0e3be29de02a1ba7aaf247493c5adf7d08e5f64b/noggin.cfg.default) has multiple security problems:
- [ ] Default secret for `FERNET_SECRET`
- [ ] Default secret for `SECRET_KEY`
- [ ] Defaults to `SESSION_COOKIE_SECURE = False`

The default configuration should not contain any secrets, to ensure that admins set their own secrets.
The default for `COOKIE_SECURE` must be set to `True` according to the [Fedora Infrastructure Application Security Policy](https://docs.pagure.org/infra-docs/dev-guide/security_policy.html#cookies).

**Comment by abompard** [comment]
This is actually a poor choice of file naming, the `noggin.cfg.default` file does not contain the defaults. It's more of an example file. The defaults are in [noggin/defaults.py](https://github.com/fedora-infra/noggin/blob/dev/noggin/defaults.py). This file does not contain defaults for the secrets and sets `SESSION_COOKIE_SECURE` to `True`.

I'll rename `noggin.cfg.defaults` to make it clearer that it's an example file.
