### ISSUE TITLE
[secaudit-blocking] Multiple remote resources used not on approved origins

### ISSUE THREAD

**Issue by puiterwijk** [fedora-infra/noggin#337]
Part of secaudit #316, blocking.

The [Fedora Infrastructure Application Security Policy](https://docs.pagure.org/infra-docs/dev-guide/security_policy.html#security-headers) lists the origins that are allowed for the CSP header. Any resources loaded from origins not listed there will be rejected by the browser, and as such are not allowed to be used.
Noggin currently refers to many external resources, for example [`https://stackpath.bootstrapcdn.com/`](https://github.com/fedora-infra/noggin/blob/0e3be29de02a1ba7aaf247493c5adf7d08e5f64b/noggin/themes/default/templates/main.html#L5), [`https://code.jquery.com/`](https://github.com/fedora-infra/noggin/blob/0e3be29de02a1ba7aaf247493c5adf7d08e5f64b/noggin/themes/default/templates/main.html#L67) and [`https://cdnjs.cloudflare.com/`'](https://github.com/fedora-infra/noggin/blob/0e3be29de02a1ba7aaf247493c5adf7d08e5f64b/noggin/themes/default/templates/main.html#L68).

**Comment by abompard** [comment]
Done in #413. I don't know if we should set the CSP header ourselves or if it is done by Fedora's front proxy. If it should be added by the application itself, do you recommend we use [Flask Talisman](https://github.com/GoogleCloudPlatform/flask-talisman)? It's recommended on [Flask's official documentation](https://flask.palletsprojects.com/en/1.1.x/security/#security-headers) in the Security Headers section.
