### ISSUE TITLE
Searching users doesn't prepend application root to URL

### ISSUE THREAD

**Issue by nphilipp** [fedora-infra/noggin#387]
When searching for users in staging (from https://admin.stg.fedoraproject.org/accounts/ which—after logging in—redirects to  https://admin.stg.fedoraproject.org/accounts/user/<your username/), it redirects to the user's page using a malformed URL without the application root `/accounts/` prepended to the path.

When finding the problem, maybe check if there are other places in the codebase where this is handled in the same (wrong) way.

**Comment by abompard** [comment]
Yeah I saw that before but never got around to fixing it. The dict returned by the search backend should contain an `url` key for the result (user or group), so that the frontend just follows it.

**Comment by nphilipp** [comment]
Mind, the `S` label :arrow_up: reflects how much time this should have taken :wink:.

**Comment by abompard** [comment]
Was fixed in 3e7cbdb5
