### ISSUE TITLE
As a registered user, I want to be able to add and remove SSH keys from my account, so that I can access Fedora systems with my current keys and disable access from old keys.

### ISSUE THREAD

**Issue by sfinn85** [fedora-infra/noggin#40]

**Comment by Jakuje** [comment]
Make sure that this allows storing multiple ssh keys not just one as it is in the current FAS.

**Comment by abompard** [comment]
I think @relrod mentionned that we may want to try certificate-based SSH access. Did I understand it right? Would that be the subject of a spike?

**Comment by ryanlerch** [comment]
Just out of interest, does anyone know how the SSH keys currently work with FAS? I see freeIPA has the ability to add SSH keys, but a little fuzzy how these are used by the applications and servers.

**Comment by Jakuje** [comment]
In current fas, there is a limitation to add only one public key in UI, which is very cumbersome and limiting if you want to access fas account from more devices and I wanted to make sure this limitation will not be brought to the next generation.

Internally, I assume there is some `AuthorizedKeysCommand` in `sshd_config` invoked, which will fetch the public key(s) for current user. Certainly, IPA can do it this way, pulling the public keys that are associated with the user account.

**Comment by ryanlerch** [comment]
@Jakuje AFAICT, it is possible with the current FAS to have multiple SSH keys:

https://lists.fedoraproject.org/pipermail/devel/2008-April/000653.html

**Comment by Jakuje** [comment]
I probably did not search deep enough in the history when I needed this few years back. But in any case, this is not intuitive and use case of different laptops does not work well with this workaround -- you usually want to add different keys from different laptops and not to remove all of them, cat them together with a new one and add them again.

**Comment by tiran** [comment]
IPA can store multiple SSH keys per user. Each key must be stored as a separate entry. You cannot cat them together.

The IPA client installer configures sshd to fetch public keys through SSSD ( ``AuthorizedKeysCommand /usr/bin/sss_ssh_authorizedkeys``). SSSD fetches the SSH key from LDAP, caches it, and delivers it to sshd.

**Comment by sfinn85** [comment]
Can be pulled into sprint 4. Let's run with SSH key for now
