### ISSUE TITLE
Review Centos theme PR and merge

### ISSUE THREAD

**Issue by StephenCoady** [fedora-infra/noggin#405]
There is a PR here: https://github.com/fedora-infra/noggin/pull/383 that needs to be reviewed and merged before we can deploy a centos variant of noggin to staging.

**Comment by szpak** [comment]
@StephenCoady The link to the PR is broken - it should be https://github.com/fedora-infra/noggin/pull/383 . Btw, it seems to be already merged.

Btw2, is it possible to test the version deployed to staging?

**Comment by StephenCoady** [comment]
@szpak yes I merged.

We don't have a centos variant deployed to staging yet, but hopefully it won't be too long. You can follow this issue here to see when it gets deployed: https://github.com/fedora-infra/aaa-tracker/issues/19
