### ISSUE TITLE
As a contributor (in any capacity), I want to request a new group, so that I can group together people working with me on my cool project.

### ISSUE THREAD

**Issue by sfinn85** [fedora-infra/noggin#41]

**Comment by puiterwijk** [comment]
I think this should just be done via an Infra ticket, as it has in the past.

**Comment by ryanlerch** [comment]
@sfinn85 @relrod this one is possibly out of scope / and or not even needed in securitas. Suggest closing?

**Comment by relrod** [comment]
@ryanlerch correct, this ticket is just for tracking and noting that. No action needed.
