### ISSUE TITLE
As a registered user, I want to temporarily disable my account, so that I can come back later if I decide to.

### ISSUE THREAD

**Issue by sfinn85** [fedora-infra/noggin#43]
Acceptance Criteria:
Spike what happens when a user is disabled and they try to login
DOD
Above is complete

**Comment by ryanlerch** [comment]
@relrod @abompard is this something that is currently a feature in FAS? does freeIPA implement the disabling of accounts, and what does this actually mean?

**Comment by abompard** [comment]
I was just thinking, if a disabled account is unable to login, then the user can't re-enable their account and "come back later". Or maybe there are different levels of "disability"?

**Comment by sfinn85** [comment]
UX and policy  - what does disable actually mean. source @sfinn85  to follow up . Self service action - ( not admin)

**Comment by relrod** [comment]
@abompard Right, if they're disabled, we'll need to use the escalated account to re-enabled them I think.

**Comment by sfinn85** [comment]
Hi @abompard 
Please see Fedora privacy policy here https://fedoraproject.org/wiki/Legal:PrivacyPolicy and some insight from Paul https://docs.google.com/document/d/1sdm36sdsyaxNQlUVLGvGbt8TB2LC9EPa8MkDbiY0lcU/edit

Will this help guide the solution or is more information needed?

**Comment by abompard** [comment]
My question is more technical: if a disabled user can't login, how do we verify that the re-enable request actually comes from them?

**Comment by StephenCoady** [comment]
Just to follow up on what we spoke about earlier, this can't be done self-service so creating a ticket is our only option. I think this is an invalid issue.

**Comment by StephenCoady** [comment]
So as a team we decided to close this ticket as it doesn't make sense. If the user disables their account then there is no way to re-enable it unless they create a ticket. If the ticket system is backed by freeipa then they will be locked out completely.
