### ISSUE TITLE
cannot scan QR code on otp token

### ISSUE THREAD

**Issue by nirik** [fedora-infra/noggin#432]
For some reason I can't seem to scan the QR code that the otp token create shows. :( 

I have tried freeotp+ and andotp android clients, and neither one seems to work.

The displayed QR code also seems very 'dense' vs the cli one I get if I enroll via cli. 

Additionally, the url that noggin shows: 

otpauth://totp/kevin@stg.fedoraproject.org:freeotp%2B%20test?issuer=kevin%40STG.FEDORAPROJECT.ORG&secret=r<edacted>&digits=6&algorithm=SHA512&period=30

ends up opening a search in my browser search provider. I assume thats meant to pass directly to freeotp?

**Comment by ryanlerch** [comment]
When testing this out on my local test setup, the QR codes / URIs do work for me on FreeOTP and Google Authenticator. I am unable to test with the android clients though. 

Can you try out this QR code with your app(s) - these are generated from my local test install. 

![Screenshot from 2021-02-08 14-01-30](https://user-images.githubusercontent.com/592259/107174653-8057e200-6a16-11eb-8fec-ab044b01ebdf.png)

**Comment by ryanlerch** [comment]
Are you able to also check if your apps can scan the QR code generated if you don't put a token name in? There might be something funky happening with the URI encoding when you set a token name (it is optional)

**Comment by nirik** [comment]
Ha ha ha. I figured out the issue and it was totally my fault. ;( 

I run firefox with an extension called dark reader (because white letters on black background is easier on my eyes) ( https://darkreader.org/ )

However, this causes the qr code to be not readable, as it expects a white background. ;( 

I guess note this in a faq and move on. Sorry for the wasted effort.
