### ISSUE TITLE
As a registered user, I want to change my password, so that I can be a responsible person who cares about security.

### ISSUE THREAD

**Issue by sfinn85** [fedora-infra/noggin#44]
AC:

A logged-in user can change their password following
They need to provide the current password again for additional security, which is checked against FreeIPA
The password is changed in FreeIPA
They don't need to login again after changing it
A log message is emitted for audit reasons.

DoD: 
all the above are met.

**Comment by ryanlerch** [comment]
This appears to be currently implemented with the http://ipa.example.com:5000/password-reset/ page.

**Comment by relrod** [comment]
Indeed.

**Comment by ryanlerch** [comment]
although, from a user point of view, this page might benefit from some improvement, like not requiring a username if the user is logged in. (or does this page make more sense to only be available to the logged in user? )

**Comment by abompard** [comment]
Yeah I agree with @ryanlerch, it's probably better to be only available to logged in users (just my +1 because I found it unusual when I looked at that page too ;-) )

**Comment by ryanlerch** [comment]
@relrod any thoughts on this? i'm a little hazy where an expired password fits into all this. Is there a scenario where a user that is not logged in might need to use this page to change their password?

**Comment by abompard** [comment]
@ryanlerch : yeah I just thought of one: when a password is expired, the user can't login but they need to change their password. So maybe two forms (with inheritance so we don't duplicate), one for logged in users so they don't have to enter their username and current password (or maybe we always want the current password to avoid unattended laptop hacking?) and one for other users?

**Comment by relrod** [comment]
- Yeah, we should ask for current password when changing password
- I guess an open question is password expiry in general. Do we want to just disable all of that? Currently in FAS we don't expire passwords. If we disable that entirely, then we can forget that usecase and just move to a post-auth password change form entirely.
- There's also the "forgot password" usecase, but that's separate from this and will be a different form that calls an email handler, etc.

**Comment by abompard** [comment]
I think we still have to handle the "password expired" case, because if a user registers with too short a password, the password setting will fail and their password will be considered expired, login will fail and they'll have to change it.

**Comment by abompard** [comment]
AC:
- A logged-in user can change their password following
- They need to provide the current password again for additional security, which is checked against FreeIPA
- The password is changed in FreeIPA
- They don't need to login again after changing it
- A log message is emitted for audit reasons.

DoD: all the above are met.

**Comment by sfinn85** [comment]
Daily stand up update: 

@ryanlerch flagged this is done and ready for review. Great work Ryan! 
@StephenCoady or @abompard can you review/test this today so we can move it done or back into progress if further work needs to be done
