### ISSUE TITLE
As a group sponsor, I want to edit information about my group, so that the people know .

### ISSUE THREAD

**Issue by sfinn85** [fedora-infra/noggin#46]

**Comment by relrod** [comment]
Yes. This ticket is mostly about documenting that and informing users to file an infra ticket to change the description or add a sponsor.

**Comment by ryanlerch** [comment]
@relrod is securitas the place where we are going to document this? or should we move this issue elsewhere?

**Comment by relrod** [comment]
@ryanlerch like #47 we could probably add a note telling group sponsors to file an infra ticket, but it's also probably not entirely necessary.

**Comment by ryanlerch** [comment]
Added an item to the FAS theme, linking to the fedora-infra queue if a sponsor is looking at the group detail page.
