### ISSUE TITLE
As a group sponsor, I want to add a new group sponsor to my group, so that the new sponsor can add and remove members from the group.

### ISSUE THREAD

**Issue by sfinn85** [fedora-infra/noggin#47]

**Comment by relrod** [comment]
This is (or should be) tracked as a documentation task, not a technical one. The workflow is that an infra ticket is filed and a global admin will add the new sponsor. The tracking here is just to make that clear.

**Comment by ryanlerch** [comment]
@relrod is securitas the place where we are going to document this? or should we move this issue elsewhere?

**Comment by relrod** [comment]
@ryanlerch we could maybe add a note in securitas somewhere? If a sponsor goes to a group they sponsor, maybe show a little banner that says "Looking to add a sponsor? File an infrastructure ticket [here]." or something along those lines. Might not be necessary though.
