### ISSUE TITLE
Note about the Fedora Code of Conduct on login page

### ISSUE THREAD

**Issue by ryanlerch** [fedora-infra/noggin#495]
There was a request to add a note to the login page of the Fedora theme, saying that logging in to noggin means they adhere to the Fedora Code of Conduct.

**Comment by mattdm** [comment]
Thanks for filing this. I've contacted Legal for some text.

**Comment by ryanlerch** [comment]
I have a few queries about this one:

AIUI, Fedora and CentOS accounts are going to be controlled by the same freeIPA backend, with just two separate instances of Noggin simply themed up for Fedora and CentOS. So do we want to put the same notice on the CentOS theme, making them adhere to the Fedora CoC?

**Comment by ryanlerch** [comment]
Another option here might be to use the user agreements feature we have.

In noggin / freeipa-fas we now have the ability to add more than one "agreement", in FAS we only had one agreement, FPCA. And this is controlled in freeipa-fas by only letting users be added to certian groups if they have signed the FPCA.

We could easil;y now add another agreement for the Fedora CoC, and make it a requirement for membership in Fedora Groups to have "signed" that agreement.

**Comment by nirik** [comment]
I would of course defer to legal/others, but I always thought it was a bad idea to make people agree to a Code Of Conduct. This provides the 'loophole' of people who don't agree to it to say they are in no way bound by it.
I think it's much better to say "If you are using any project resources, you must follow the code of conduct"

**Comment by ryanlerch** [comment]
> I would of course defer to legal/others, but I always thought it was a bad idea to make people agree to a Code Of Conduct. This provides the 'loophole' of people who don't agree to it to say they are in no way bound by it.
> I think it's much better to say "If you are using any project resources, you must follow the code of conduct"

Fair enough, but i'm worried a similar loophole might occur if we only have the CoC agreement note on the Fedora Noggin, and not the CentOS one. In theory, if we only put it on the Fedora noggin, a fedora contributor could claim they only signed in  with the centos one, and never saw the note about the CoC.

**Comment by ryanlerch** [comment]
Additionally, @mattdm should this note also be included on the ipsilon login page also? People are more likely to use that to log in day-to-day

**Comment by mattdm** [comment]
+1 to what Nirik said about agreement.

Rich Bowen is the person to ask about the CentOS situation.

And yes, I think putting it on Ipsilon is good.

**Comment by ryanlerch** [comment]
@mattdm any update from legal on the wording here?

**Comment by ryanlerch** [comment]
@rbowen any thoughts on this one from the CentOS side?

**Comment by mattdm** [comment]
Yes. It should just be:

> By using a Fedora account, you agree to follow the [Fedora Code of Conduct](https://docs.fedoraproject.org/en-US/project/code-of-conduct/).

We should also use the text from https://fedoraproject.org/wiki/Legal:Fedora_Project_Contributor_Agreement#Overview for the FPCA checkbox:

> The only purpose of the Fedora Project Contributor Agreement (FPCA) is to ensure that Fedora has default permission to use your contributions under a permissive free license (either MIT for software or CC BY SA for content). You may contribute under any other acceptable Fedora license, the FPCA simply sets a default if no license is specified.
> 
> Nothing in the FPCA takes anything away from you. You retain ownership of your contributions.

**Comment by nirik** [comment]
Can we say "By using Fedora project resources, you agree to follow the..." instead of "By using a Fedora account..." ?

**Comment by mattdm** [comment]
Let me check back. I think this was specifically to go next to the fedora account system, so that's why the mention of account.

**Comment by ryanlerch** [comment]
> 
> We should also use the text from https://fedoraproject.org/wiki/Legal:Fedora_Project_Contributor_Agreement#Overview for the FPCA checkbox:
> 
> > The only purpose of the Fedora Project Contributor Agreement (FPCA) is to ensure that Fedora has default permission to use your contributions under a permissive free license (either MIT for software or CC BY SA for content). You may contribute under any other acceptable Fedora license, the FPCA simply sets a default if no license is specified.
> > Nothing in the FPCA takes anything away from you. You retain ownership of your contributions.

That text is actually stored in FreeIPA, so we need to update that there (maybe that needs to be a seperate ticket in https://github.com/fedora-infra/aaa-tracker/)
