### ISSUE TITLE
As a registered user, I want to learn how to join a new group, so that I can participate in it and help out.

### ISSUE THREAD

**Issue by sfinn85** [fedora-infra/noggin#50]
Acceptance Criteria:

- Generic note ""Want to join this group? Talk to one of these people for information"  to be added to the group page near the sponsor list

DOD:

- AC complete 

Est S

**Comment by ryanlerch** [comment]
@relrod any idea what this one might entail? are we thinking a link to a wiki page (this might work for SIGs and other groups like the Design Team), but not sure how this works for other groups.

**Comment by relrod** [comment]
This could probably be as simple as "Want to join this group? Talk to one of these people for information:" somewhere near the sponsorship list. Alternatively we could probably just close this and say it's not relevant for securitas.

**Comment by ryanlerch** [comment]
i'm leaning towards just closing this one off IMHO.

**Comment by sfinn85** [comment]
What is the current process for a user looking to join a group? If it is straight forward, the norm for a user, what they would expect then lets not change but if it is not straight forward UX flow we might need to look at improving it. Thoughts @abompard @relrod @ryanlerch

**Comment by sfinn85** [comment]
linked to #20
