### ISSUE TITLE
allow for configurable blocklist of account names

### ISSUE THREAD

**Issue by nirik** [fedora-infra/noggin#512]
In fas we had a list of usernames that were disallowed to be created. 
Would be great to have that in noggin as well. 

You can see the list in: 
https://pagure.io/fedora-infra/ansible/blob/main/f/roles/fas_server/templates/fas.cfg.j2#_76

Rationale:
* Sometimes we create email aliases, we don't want someone to make a user with the same name and never be able to get their email or confuse the alias people (examples: fpl@fedoraproject.org going to the fedora project leader, etc)
* We don't want users to create accounts that overlap with system accounts, as this could give them privs or cause issues with system accounts (examples: root, sync, ftp, bodhi, kojibuilder, etc)

 Likely in the new noggin world we would want to either fold the CentOS list into ours.

**Comment by arrfab** [comment]
From irc discussion, I guess we can approach this through two different angles : 
 * we have that 'disallow list' in noggin, to forbid people register with specific nick , but that needs some dev in noggin
 * or we can also just create these users in IPA, without fas attributes (not showing up through noggin/fasjson), and disable these accounts directly : that ensures that names are "protected" so nobody can create account with such nick (already taken)

**Comment by abompard** [comment]
We created the accounts in IPA
