### ISSUE TITLE
(S) As a AAA developer I want my PR to be automatically merged if they are approved and meet a certain standard so that I can focus on development work

### ISSUE THREAD

**Issue by sfinn85** [fedora-infra/noggin#53]
Acceptance Criteria
================

1. Project is using Mergify to automate the PR merging.
2. Mergify is configure to require the CI to pass and 1 person to approve the PR

**DOD**
As above

**Comment by abompard** [comment]
I don't have access to the apps enabled on the securitas repo. I'm trying to add DCO and Mergify (for #53).
@relrod, could you enable them or give me the permissions to do it? Thanks.
