### ISSUE TITLE
Scrollbar on empty page

### ISSUE THREAD

**Issue by abitrolly** [fedora-infra/noggin#535]
![image](https://user-images.githubusercontent.com/8781107/111428069-14008a80-8708-11eb-9925-ee35a4a46bc1.png)

**Comment by abompard** [comment]
Are you sure there's not a footer down the page?

**Comment by abitrolly** [comment]
@abompard there is. If I scroll down.

I can not recheck right now, because I don't remember the URL and there is no URL at https://github.com/fedora-infra/noggin
