### ISSUE TITLE
Import script

### ISSUE THREAD

**Issue by sfinn85** [fedora-infra/noggin#55]

**Comment by relrod** [comment]
I *think* this is meant to track this: https://github.com/relrod/fas2ipa ?

But issues should probably be tracked there (or in a CPE copy of that repo) instead.

**Comment by sfinn85** [comment]
HI @relrod 

same reason as my other comments, can you pull this on to the to do lane on AAA Board thanks

**Comment by abompard** [comment]
I'm not sure what we must do, it'd be great if we could have a DoD for this ticket.

**Comment by relrod** [comment]
AC:

* consensus and plan reached for dealing with human names in IPA
* fas2json script tested. It's already been mostly tested, but should be tested some more.

**Comment by sfinn85** [comment]
Sprint planning 3 update: AC is more notes.
Unsure of 'tested some more' means? How do we verify 60k users?  TM do not have access. What does testing the script look like? Need access to either database to test. 
Script has been moved Fedora Infra. Script connects directly to Free IPA, possibly a Free IPA instance as a staging environment 

2 user stories identified 

1. Access to user database- log ticket on infra tracker (s)


2. Script to migrate data to Free IPA ( Dependent on https://github.com/fedora-infra/freeipa-fas/issues/11 ) ( Unknown - L ) 
AC:
1. Implement name changes
2. Run the script - ensure the output is what is the input ( test ) run script multiple times without removing database
3. Verify 
4. Fix if any issues 

DOD:
Script can import data from FAS into Free IPA without any errors.
Verify Plan for accounts that do not have first name and last name - how these are handled

**Comment by sfinn85** [comment]
This large user story has been broken down into two smaller user stories:

https://github.com/fedora-infra/securitas/issues/102
https://github.com/fedora-infra/securitas/issues/103

I will remove this user story from the project board back to the issues log. ( When I gain permission to do so) I don't want to delete this user story as we have some information on here that we don't want to lose. The user stories created have link to this user story added.

**Comment by ryanlerch** [comment]
Going to close this one off. it is referenced to by the 2 issues that it was split into.
