### ISSUE TITLE
Links to a group's mailing list are broken

### ISSUE THREAD

**Issue by phuzion** [fedora-infra/noggin#552]
This afternoon I noticed that links to a group's mailing list were broken.

If you go to https://accounts.fedoraproject.org/group/sysadmin/ and click on the link next to the 📧 icon, that says infrastructure[at]lists.fedoraproject.org, you will be brought to https://accounts.fedoraproject.org/group/sysadmin/infrastructure@lists.fedoraproject.org, which 404s.

[In FAS2](https://admin.fedoraproject.org/accounts/group/view/sysadmin), the comparable link would go to the proper location, which is the list info page. This allows a user to view the mailing list history and subscribe to the list.

When addressing this bug, please note that there are groups that host their mailing lists on systems other than lists.fedoraproject.org, so the fix is not as simple as concatenating the hyperkitty URL to the group name. Take, for example, [fedora-hams](https://accounts.fedoraproject.org/group/fedora-hams/) who hosts their mailing list on the kernelnewbies.org mailing list system.

**Comment by abompard** [comment]
Yeah we're missing a `mailto:` in the link.

**Comment by jossperdomo** [comment]
Hello @abompard and @phuzion ! I would like to work on this issue :) Could you please tell me if add `mailto:` only in the template instead of the `mailing_list`is enough? I saw you handle IRC channels added it `irc://` to get a full link to these channels.

**Comment by phuzion** [comment]
While making the link a `mailto:` would technically fix the 404 issue, I'd argue that just making the link a `mailto:` link doesn't fully replicate the feature from FAS2.

In FAS2, the link isn't a `mailto:` link, it's a link to the list's admin settings page (on Mailman). See the FAS2 link I provided in the original post.

I think that a better solution would be either:

* Make the link point to the lists's archives OR
* Make two links, one of which a `mailto:`, and the other go to the archives.

**Comment by abompard** [comment]
Even though we're not systematically trying to replicate FAS2 features, I agree that linking to the list admin settings page would be a better solution. However, there is currently no mailing list url in the LDAP schema, and before we add one I'd like to make sure we have considered all options.

@josselineperdomo Thanks for the help! An easyfix would be to add the mailto to the template, indeed. It may not be ideal but at least it'll fix the broken link quickly while we think of a better solution.

**Comment by jossperdomo** [comment]
I'm not able to see FAS2 link because when I tried signing up it returned a 500 error. I created my account at Fedora Accounts.

Does FAS2 show all the mailing lists as an archive link (e.g.: https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/ for devel@lists.fedoraproject.org)?  

There are groups with lists outside fedoraproject.org, if we are taking into account those cases, do you suggest update automatically these archive links?

**Comment by phuzion** [comment]
The link in FAS2 looks like this:

**Mailing List:** [infrastructure@lists.fedoraproject.org](https://lists.fedoraproject.org/mailman/listinfo/infrastructure)  

One possible solution for Noggin would be something like this:

✉ [infrastructure@lists.fedoraproject.org](mailto:infrastructure@lists.fedoraproject.org) [[archive](https://lists.fedoraproject.org/archives/list/infrastructure@lists.fedoraproject.org/)]

**Comment by jossperdomo** [comment]
I got it! I'm going to work on this. If I have any other doubts, I'll reach out to you again. Thanks!

**Comment by abompard** [comment]
@phuzion We merged the quickfix to avoid the broken link, but could you please file an issue for the mailing list URL enhancement you're proposing? I think it's an interesting suggestion.
