### ISSUE TITLE
GPG key fingerprint field too short

### ISSUE THREAD

**Issue by michel-slm** [fedora-infra/noggin#556]
# Describe what you would like us to do:

In the previous FAS, I upload the text of my GPG key. After the migration to Noggin, only the fingerprint is displayed (but I can have 3 of them). This is presumably by design so instead of hosting the public keys, people who need GPG keys would look them up elsewhere and verify the fingerprint?

One issue: the field for fingerprint only takes 16 characters, but modern fingerprints are longer, e.g.: for my current key
5DCE2E7E9C3B1CFFD335C1D78B229D2F7CCC04F2

This shows up in Noggin as 5DCE2E7E9C3B1CFF

In this case I think if we only keep 16 characters, we should keep the last 16 characters, not the first 16 characters.

My current key is hosted with WKD so it's a bad example, but here's an example with my expired old key that is in the keyservers. Note that searching by a 16-character fingerprint prefix fails but searching by a 16-character suffix works

```
~ 
❯ gpg --search EA5DC40D88BD97AA2EA5A84C4EA1777DAA582584
gpg: data source: https://hkps.pool.sks-keyservers.net:443
(1)     Michel Alexandre Salim (personal) <michel@michel-slm.name>
        Michel Alexandre Salim (fedora) <salimma@fedoraproject.org>
          4096 bit RSA key 4EA1777DAA582584, created: 2017-02-09, expires: 2018-02-09 (expired)
Keys 1-1 of 1 for "EA5DC40D88BD97AA2EA5A84C4EA1777DAA582584".  Enter number(s), N)ext, or Q)uit > q
gpg: error searching keyserver: Operation cancelled
gpg: keyserver search failed: Operation cancelled

~ took 4s 
❯ gpg --search EA5DC40D88BD97AA                        
gpg: data source: https://hkps.pool.sks-keyservers.net:443
gpg: key "EA5DC40D88BD97AA" not found on keyserver
gpg: keyserver search failed: Not found

~ took 3s 
❯ gpg --search 4EA1777DAA582584 
gpg: data source: https://hkps.pool.sks-keyservers.net:443
(1)     Michel Alexandre Salim (personal) <michel@michel-slm.name>
        Michel Alexandre Salim (fedora) <salimma@fedoraproject.org>
          4096 bit RSA key 4EA1777DAA582584, created: 2017-02-09, expires: 2018-02-09 (expired)
Keys 1-1 of 1 for "4EA1777DAA582584".  Enter number(s), N)ext, or Q)uit > 
gpg: signal 2 caught ... exiting
```

**Comment by keszybz** [comment]
Also, I think it would be reasonable to refuse to display key identifiers shorten than 16 characters.
(We used to use 8 chars to identify keys, but 8 char identifiers have all been spoofed, and are useless).

**Comment by nirik** [comment]
It might also be nice to have the entire pubkey there if possible. This would allow people to get it from us rather than hunting around and trying to find a mirror with that key on it.

**Comment by nphilipp** [comment]
The field in FAS hasn't been used consistently, I've seen 8 & 16 character key ids, with whitespace separating 4 digit blocks, colons separating 2 digit blocks or without, full keys, finger prints, "linux" and the digit 8. I'd suggest either increasing the length of the key id field to 40 characters or add a separate field for fingerprints, and another field for the full pubkey. This needs work in the freeipa-fas plugin plus frontend work here.
