### ISSUE TITLE
password reset not working?

### ISSUE THREAD

**Issue by pypingou** [fedora-infra/noggin#564]
I have an account with OTP configured.
I'm able to login in the UI just fine and ssh in the infra fine as well.

I asked to reset my password as someone on IRC was reporting a 500 error when following that process.

I've received my email from FAS with the expected URL: https://accounts.fedoraproject.org/forgot-password/change?token=....

When visiting this page:
* the footer seems off, it doesn't stick to the bottom of the screen 
* I was not able to change my password, I entered the same one as I currently use, my OTP and I kept getting back: ``Could not change password, please try again.``

**Comment by abompard** [comment]
I tired just now and I can't reproduce it, could you try again please?

**Comment by gridhead** [comment]
Closing this as stale for now.

This issue would be definitely revisited if a similar issue is encountered down the road.
