### ISSUE TITLE
Use Fedora logo on OTP application

### ISSUE THREAD

**Issue by smooge** [fedora-infra/noggin#565]
Filed in Fedora Infrastructure but better suited here
i am starting to have a bunch of OTP code on my phone, and some of them display a logo of the associated service. Fedora don't.

I think it would be cool and useful if Fedora logo was displayed. I do not know how that's done, but this seems standard (cause Nintendo, Gandi and Github manage to do it).

From a quick look at Freeotp, that's using a "image" parameter ( https://github.com/freeotp/freeotp.github.io/blob/master/qrcode.js#L28 ).

I guess support need to be added in noggin, around https://github.com/fedora-infra/noggin/blob/dev/noggin/controller/user.py#L180

This seems like a easy contribution for a new developer.

**Comment by lgriffin** [comment]
This service will be shared between CentOS and Fedora so I'm unsure how a logo would work unless we could give people a choice of logos to use?

**Comment by arrfab** [comment]
Well, IPA backend will be shared, but noggin frontend instances will be different, also for the fedora / centos themes applied (see for example https://accounts.stg.centos.org/ and https://accounts.stg.fedoraproject.org/)

If the code would permit that to be in used theme (that's a config option , and some themes already exist : https://github.com/fedora-infra/noggin/tree/dev/noggin/themes and https://github.com/fedora-infra/noggin/blob/dev/noggin/defaults.py#L11) , that can be good to implement (I'd tagged this as RFE)

**Comment by mscherer** [comment]
As a alternative, I am sure we can find some not too ugly logo that mix Fedora and Centos one, but that would requires someone with actual design skills (e.g., not me). 

And the feature would still be useful for communities that do not have shared backend, e.g., OpenSUSE.

Also, the original bug on pagure ( https://pagure.io/fedora-infrastructure/issue/9797 ).
