### ISSUE TITLE
Missing notifications?

### ISSUE THREAD

**Issue by voxik** [fedora-infra/noggin#567]
I have just sponsored `mspacek` into `packager` group, but I have not received any notification from `packager-sponsors@fedoraproject.org`, is that intentional? Or am I impatient and the notification is queued somewhere for processing?

**Comment by abompard** [comment]
Currently, only a fedmsg is sent on the bus (topic is `fas.group.member.sponsor`). When we revamp FMN, we'll need to remember to trigger actions on this message topic.
