### ISSUE TITLE
As a registered user, I want to see the email addresses of other contributors in their profile.

### ISSUE THREAD

**Issue by justwheel** [fedora-infra/noggin#568]
# Summary

The email address associated with a Fedora Account should be displayed in the user's profile to other registered users, if their account is NOT set to `private`.

# Background

In FAS2, ~75% of the time I used it to look up the email address of another contributor. This might be to add them to an email, invite them to a calendar event for a meeting, or share their connection details with another contributor who needs their help. However, in Noggin, the email address does not appear in the profile. It is not apparent if a registered user is able to look up another Fedora contributor's email address at all in the new system.

**Why not use `@fedoraproject.org` aliases?** You must have FAS+1 for this email alias to work. Often I reach out to new contributors who are just getting started, and I need to know their real email address, not a non-existent email alias.

**What about privacy?** `zodbot` still shows email addresses if you use `.fasinfo` in chat. To me, this is a greater privacy concern than showing the email address in Noggin. Any unauthenticated user can interact with `zodbot` and query the Fedora Account system this way in publicly-logged channels, even for `private` accounts' email addresses. If this user story is declined, then email addresses should also be removed from `zodbot`'s `.fas` and `.fasinfo` command.

**What about RHBZ email address, since that shows up in the profile?** Not all Fedora contributors use Red Hat Bugzilla. A lot of important work also happens outside of Bugzilla. Not every Fedora contributor will know to authenticate or fill this out, especially if they are new to the community.

# Details

This is prominent info, so it should be near the top. Something like this makes me happy:

![Screenshot of profile mockup with an email address](https://user-images.githubusercontent.com/4721034/113426786-f8e97800-93a1-11eb-8dbc-35791ed4284e.png)

# Outcome

Easier to look up contact information for and connect with another Fedora contributor

**Comment by abompard** [comment]
This sounds like a valid enhancement, since email addresses can also be queried via FASJSON anyway.

**Comment by funnelfiasco** [comment]
This would be very helpful for the Magazine editor workflow, as we generally use zodbot queries to get a user's email address to add them to the Taiga board.
