### ISSUE TITLE
Use seperate UI field for otp token

### ISSUE THREAD

**Issue by nirik** [fedora-infra/noggin#572]
Currently the noggin login page has just a username/password username/password+otp pair of fields. 
It would be nice to split the otp out and make it it's own (optional) field. 
This would help folks that use web password managers, and make the UI a little nicer. :)

**Comment by jossperdomo** [comment]
Hello @nirik! I would like to work on this issue :) I recently started to get familiarized with noggin and I think it should be set the form in the template, isn't it?

**Comment by abompard** [comment]
@josselineperdomo Yeah, it's a combination of template changes, form changes (the forms are defined in python in the `forms` subfolder) and controller change to concatenate those two fields.

**Comment by jossperdomo** [comment]
@abompard I did a [PR](https://github.com/fedora-infra/noggin/pull/587/files) to fix it. I added a unit test, please let me know if the cassette for the `test_login_with_otp` is properly done.
