### ISSUE TITLE
Lowercase the usernames when users want to reset their password

### ISSUE THREAD

**Issue by abompard** [fedora-infra/noggin#573]
If a user uses a mixed-case username to request a password change token, the lock file will be created with this mixed-case username. The IPA API call will succeed because IPA automatically lowercases usernames. But when the lock needs to be removed in the next part of the process, it will try to remove the lowercase version, not find it, and traceback.

We should lowercase the user input before creating the `PasswordResetLock` instance.

**Comment by akanshak984** [comment]
@abompard I would like to work on this. Can you guide me on how to reproduce this on my local?

**Comment by abompard** [comment]
Sure! Our contributor guide is here: https://noggin-aaa.readthedocs.io/en/latest/contributing.html
But it may be out of date in places so if it does not work feel free to ping me here or in IRC in #fedora-aaa.
Thanks for your help! :-)

**Comment by akanshak984** [comment]
> Sure! Our contributor guide is here: https://noggin-aaa.readthedocs.io/en/latest/contributing.html
> But it may be out of date in places so if it does not work feel free to ping me here or in IRC in #fedora-aaa.
> Thanks for your help! :-)

Hi @abompard I'm unable to set this up on my local using the link you provided, and I have no idea how to ping you (or anyone) in IRC.
Attaching below the screenshot for the error i'm getting.
system details: Ubuntu 18.04.3 LTS


![Screenshot from 2021-04-09 17-34-58](https://user-images.githubusercontent.com/39851943/114177522-201fe680-995a-11eb-8af3-fb692cdf735f.png)

**Comment by abompard** [comment]
Ah, we haven't tested development on Ubuntu, since Noggin is the web frontend for the authentication system in Fedora (and soon OpenSuSE I think).
You're apparently missing a vagrant provider, it should be in the deb-equivalent packages of libvirt and vagrant-libvirt. I don't know if Ubuntu has equivalents of vagrant-hostmanager and vagrant-sshfs but that's likely. I don't know how the packages are named though.

**Comment by gridhead** [comment]
@akanshak984, please try installing VirtualBox on your local environment. Here are some links that you may find helpful.
- https://itsfoss.com/install-virtualbox-ubuntu/
- https://phoenixnap.com/kb/install-virtualbox-on-ubuntu

(That is if you decide VirtualBox to be your default provider. You can pick something else as well.)

**Comment by akanshak984** [comment]
> @akanshak984, please try installing VirtualBox on your local environment. Here are some links that you may find helpful.
> 
> * https://itsfoss.com/install-virtualbox-ubuntu/
> * https://phoenixnap.com/kb/install-virtualbox-on-ubuntu
> 
> (That is if you decide VirtualBox to be your default provider. You can pick something else as well.)

@t0xic0der I have installed VirtualBox, Now when I try to run Vargant Box I get this 

![Screenshot from 2021-04-10 12-52-24](https://user-images.githubusercontent.com/39851943/114262229-60d03c00-99fc-11eb-8e47-3af45332fc07.png)

**Comment by akanshak984** [comment]
> Ah, we haven't tested development on Ubuntu, since Noggin is the web frontend for the authentication system in Fedora (and soon OpenSuSE I think).
> You're apparently missing a vagrant provider, it should be in the deb-equivalent packages of libvirt and vagrant-libvirt. I don't know if Ubuntu has equivalents of vagrant-hostmanager and vagrant-sshfs but that's likely. I don't know how the packages are named though.

Hi @abompard , I have tried to set-up the development enviornment on Fedora too.. But I'm still unable to do that.
When I run `vagrant up`, it gives me error in `TASK [noggin : Enroll system as IPA client] ************************************` which i'm unable to understand. Also the error is quite large, so i cannot post here.
What should I do?

Kindly advise.
