### ISSUE TITLE
[RFE] Show FPCA status in UI

### ISSUE THREAD

**Issue by funnelfiasco** [fedora-infra/noggin#575]
The old FAS included "cla_fpca" in the group list for a user. This is helpful to verify that a user has signed the Fedora Project Contributor Agreement. The account system has this information in the `agreements` data so it can be queried via fasjson. However, it would be nice to indicate this in the Noggin web UI.

**Comment by abompard** [comment]
Apparently JWF had the same idea in #576, I'm closing this one in favor of the other. Thanks!
