### ISSUE TITLE
Add a link where to file bugs 

### ISSUE THREAD

**Issue by kparal** [fedora-infra/noggin#598]
When I open https://accounts.fedoraproject.org (logged in or out), I don't see any information pointing me to this project ( https://github.com/fedora-infra/noggin ). So if users want to file bugs, they don't know where to go. If they search for "fedora accounts", they are very unlikely to find this "noggin" project, and even if they did, they wouldn't understand that it's the right one, because "noggin is a self-service portal for FreeIPA" will not help them.

Please add a footer or something pointing users to this project page, thank you.

**Comment by phuzion** [comment]
This appears to have been resolved with 5d09c0e33b. Can you confirm that this is the case?

**Comment by kparal** [comment]
Yes, I had to search for a while, but found "Powered by noggin v1.3.0 (stable:ee5abd4)" at the very bottom of https://accounts.fedoraproject.org/  :-) Thanks.
