### ISSUE TITLE
(S) Wireframe the new user form. This is the form that a user completes to create a new account.

### ISSUE THREAD

**Issue by sfinn85** [fedora-infra/noggin#6]

**Comment by sfinn85** [comment]
**Acceptance Criteria:**

- Visual wire frame of new user form
- Fields ( TBC )
- Working doc 

**DOD:**
All above completed

**Comment by ryanlerch** [comment]
First pass at the signin / signup page,

![signin-signup](https://user-images.githubusercontent.com/592259/71964706-e12c4e00-3249-11ea-908f-b68f84662265.png)

**Comment by StephenCoady** [comment]
Looks good to me. The only thing I would add is that we will probably have an email field in the new account section.

**Comment by sfinn85** [comment]
Looks good Ryan, but is the same as https://github.com/fedora-infra/securitas/issues/7 . see feedback on that ticket. Thanks
