### ISSUE TITLE
The "Leave group" button is too hidden, when there are many sponsors

### ISSUE THREAD

**Issue by kparal** [fedora-infra/noggin#600]
The `Leave group` button is attached to the `Members` section. However, if there are a lot of sponsors, the button is not visible on the screen at all. And if people don't know where to look for it, they might not find it. As an artificial example, here's the Fedora's `packager` group:
https://accounts.fedoraproject.org/group/packager/
You have to scroll about 5 pages down (on my screen) to about middle of the webpage, where you can finally find a very subtle `Leave group` button.
It would make more sense to have the button at the very top, together with group description etc.

**Comment by abompard** [comment]
It would also probably make sense to have a button to leave a group from the user's profile page, where their groups are listed.

**Comment by abompard** [comment]
@ryanlerch Could you have a look at this when you have time please?
