### ISSUE TITLE
login with email address succeeds for Ask Fedora but is seen as a new account

### ISSUE THREAD

**Issue by mattdm** [fedora-infra/noggin#606]
If users try to log in to [Ask Fedora](https://ask.fedoraproject.org/) with their email address instead of their username, this succeeds but the user is created as a new, different user on the site. I tested this and got:

![Screenshot from 2021-04-23 11-23-01](https://user-images.githubusercontent.com/123367/115893731-89a5f780-a426-11eb-9609-c74da9d4a8bb.png)

Either Fedora Accounts should not allow email-based login, or it should return the Fedora Account ID as the username to the system requesting auth information rather than something new. (I'm not sure if "mattdm1" is coming from Fedora Accounts or is created by Discourse in response to getting an email address as the identifier?)

**Comment by puiterwijk** [comment]
So, this is caused by Ipsilon just taking the entered username as the username for following protocols if the login plugin accepted the username.
This could be solved by changing the Ipsilon mapping to ignore the built-in `_user` value, and instead get that from the username attribute returned by IPA.

**Comment by abompard** [comment]
Thanks Patrick! I've made the change in staging ipsilon, is there a way to test logging into `ask` using the staging ipsilon? Do we have a staging ask instance?

**Comment by justwheel** [comment]
Note that soon, the Fedora Ask site will be migrated into the existing Fedora Discussion site, where they will then both live at https://discussion.fedoraproject.org/

**Comment by ryanlerch** [comment]
@abompard do you know if this was ever resolved?
