### ISSUE TITLE
Make sure changing second factor requires two-factor authentication

### ISSUE THREAD

**Issue by AdamWill** [fedora-infra/noggin#61]
I reported [an issue about this](https://github.com/fedora-infra/fas/issues/279) for the current FAS, and it was suggested I should file it as a plan for this new one instead.

With the old FAS, if an account has a second factor enrolled, you can replace it with a different second factor without authenticating using the existing second factor (you only need to provide the account password). This obviously makes the second factor almost useless.

If an account has one or more second factors set up already, then removing it or adding a new one should require the user to authenticate using one of the existing second factors. Only adding the very first second factor should be possible using only the account password.

**Comment by tyll** [comment]
How do you see users recover their account when they lost access to their only 2FA token?

**Comment by AdamWill** [comment]
Well I'd ask someone more expert for a best practice, but if you forced me to pick, I'd suggest a manual process where an admin tries to ascertain as best as they can based on available info and any existing knowledge that they're talking to the right person. Also, the important thing to do is try as hard as possible to make sure people don't get into that situation: no-one should have only one second factor. If we're building a new system it shouldn't assume *only* Yubikeys will be used as second factors, it should ideally handle use of all sorts of second factors, like Google or Github etc. do, and specifically encourage people to set up at *least* two when first configuring 2FA. And perhaps also providing a sheet of emergency one-time codes, like Google does when you turn 2FA on, that you're meant to print out and keep in a safe place. When an emergency code is used (and maybe when any unusual second factor is used on an account?) the system should email the user to let them know, just in case it wasn't them.

**Comment by relrod** [comment]
Yeah. The current practice (ignoring the horrible original issue that you pointed out in current FAS) is that it's a manual review to reset 2fa. If there's a GPG key set on the account and a user signs an email using that key, that's usually considered enough (again, ignoring the issue you pointed out). There are also security questions in current FAS that people can use. Otherwise there are some other ways we've had people verify. But it's a manual process.

**Comment by ryanlerch** [comment]
Currently, in noggin we have now implemented 2FA with OTP tokens. If you add a OTP token to your account, you are required to use it to log into noggin, and thus change your 2FA. So i think we can close this one as done.
