### ISSUE TITLE
(L) As a AAA developer I want Continuous Integration to run on each PR so that new code meets a certain standard

### ISSUE THREAD

**Issue by abompard** [fedora-infra/noggin#63]
## Acceptance Criteria

* Continuous Integration is using the tox tool to orchestrate steps.
* Code base complies with PEP8 (flake8)
* Code base is uniformly formatted (black)
* Code base is secured (bandit)
* Dependencies licences are checked (liccheck)
* Dummy tests ( Unit & Integration) to make sure they are run in CI
* Unit tests and coverage are run
* Integration tests are run.

## DOD
All above completed

**Comment by abompard** [comment]
This user story is actually not entirely finished, we need the CentOS people to activate our project in Centos CI. It should be tracked by [their ticket #16901](https://bugs.centos.org/view.php?id=16901).

**Comment by sfinn85** [comment]
Ok , lets create a subtask for this ,is that possible on github?

**Comment by sfinn85** [comment]
Follow up with @abompard
