### ISSUE TITLE
Adding new chocies for non binary people on Fedora accounts

### ISSUE THREAD

**Issue by Ahcatan** [fedora-infra/noggin#646]
When trying to update pronouns on https://accounts.fedoraproject.org/user/ profile, the system gives only one reduced choice when gender fluid people might want to use several pronouns like she/they or he/they and this is not possible. 

Could other choices be introduced?

**Comment by bittin** [comment]
have the same problem +1

**Comment by justwheel** [comment]
There is a wider discussion about this request in [fedora-diversity#203](https://pagure.io/fedora-diversity/issue/203). It is likely that the Fedora Accounts system is not the only system we have where this RFE applies.

I am curious, would it be enough to allow up to two selections for pronouns? Are there other use cases to take into consideration? What should the new options be?

Maybe @mscherer has some thoughts here too.

**Comment by abompard** [comment]
This is related to #220. Allowing multiple options among the proposed choices seems possible. It would also not be too invasive schema-wise since it's simple to change a field to be multi-valued.
