### ISSUE TITLE
Language clean up

### ISSUE THREAD

**Issue by StephenCoady** [fedora-infra/noggin#647]
There are some usages of the word master that we could remove, [here](https://github.com/fedora-infra/noggin/blob/dev/devel/ansible/roles/common/vars/main.yml#L4) and [here](https://github.com/fedora-infra/noggin/blob/dev/devel/ansible/roles/freeipa/tasks/main.yml#L27)

We also have [master.html](https://github.com/fedora-infra/noggin/blob/dev/noggin/templates/master.html) which we could rename, along with the references to it, [here](https://github.com/fedora-infra/noggin/blob/dev/noggin/themes/fas/templates/main.html#L1), [here](https://github.com/fedora-infra/noggin/blob/dev/noggin/themes/centos/templates/main.html#L1), [here](https://github.com/fedora-infra/noggin/blob/dev/noggin/themes/default/templates/main.html#L1) and [here](https://github.com/fedora-infra/noggin/blob/dev/noggin/themes/openSUSE/templates/main.html#L1)

We can also swap usage of the deprecated [whitelist_externals](https://github.com/fedora-infra/noggin/blob/dev/tox.ini) to [allowlist_externals](https://tox.readthedocs.io/en/latest/config.html#conf-allowlist_externals)

**Comment by ADHIKSHA** [comment]
Will love to work on this issue!

**Comment by abompard** [comment]
Fixed by #648
