### ISSUE TITLE
(S) As a AAA developer I want to have Contribution Guidelines and Developer documentation so that it is easy to contribute to my project

### ISSUE THREAD

**Issue by ryanlerch** [fedora-infra/noggin#65]
**Note** dependency: freeipa-fas: 13, #63 need to happen first.

** Note ** This was originally filed as fedora-infra/freeipa-fas: 17

# Acceptance Criteria
* Project contains documentation that describe how to setup the development environment
* Project contains documentation that describe how to run the CI
* Project contains documentation that describe how to contribute

### DOD
* All above completed
* Reviewed

**Comment by abompard** [comment]
Blocked by PR #62 (US #63) because it needs the setup that is done there

**Comment by abompard** [comment]
For this user story I think PR #70 would be useful: it will make our documentation always accessible and buildable.

**Comment by sfinn85** [comment]
Great to see this in ready for review. Does the team member reviewing this, know what they need to review? :)  Like the note about 70, how do we carry out this?

**Comment by abompard** [comment]
PR #70 is merged now, and the PR #62 (merged too) has added a lot of developer documentation.
I guess that what's left in this ticket is to review the developer documentation we currently have and decide whether we find it clear and complete or not. It is [visible on readthedocs](https://securitas.readthedocs.io/en/latest/contributing.html).

**Comment by sfinn85** [comment]
Thanks @abompard.

@ryanlerch @relrod  @StephenCoady  this is ready for your review if you have capacity.

Thanks all

Sarah

**Comment by sfinn85** [comment]
@StephenCoady  can you review this today so we can move it into done if you are happy with it before the sprint ends later today?

**Comment by StephenCoady** [comment]
Sorry @sfinn85 this slipped through because the individual PRs were reviewed separately. Happy with the docs overall. Moving to done.
