### ISSUE TITLE
Registration form: "I am over 16 years old" label not linked to checkbox

### ISSUE THREAD

**Issue by jaller94** [fedora-infra/noggin#658]
## Steps to reproduce the issue
0. Don't be logged in.
1. Go to https://accounts.fedoraproject.org/
2. Click on "I'm over 16 years old"

## Expected
Clicking the label toggles the checkbox. Also, screen readers know that this is the label for the checkbox.

## Actual
Clicking the label does nothing. Screen readers have to guess that this is the label for the checkbox.
The `<label>` is missing a `for` attribute with the value of the `<input>`'s `id`.

## What it looks like
![Clicking "I am over 16 years old" doesn't toggle the checkbox.](https://user-images.githubusercontent.com/10872136/120812813-9fdac380-c54d-11eb-86e3-176f1c28853c.gif)

## What it should look like
![Clicking "I am over 16 years old" toggles the checkbox.](https://user-images.githubusercontent.com/10872136/120812904-b6811a80-c54d-11eb-859b-3e484c6eb1af.gif)

## Code in question
https://github.com/fedora-infra/noggin/blob/7357a1d3562dd3108de2ec17d6404387a7551a4d/noggin/form/register_user.py#L42-L43

This may be an upstream issue of wtforms and their [BooleanField](https://github.com/wtforms/wtforms/blob/a55be54c0b8487f81e8c0f61279818ada0bd2075/src/wtforms/fields/core.py#L849). However, I'm not familiar with either projects and couldn't find the code in question.

**Comment by Cliftonz** [comment]
Literally was about to report this too.
I agree that the words should be linked to the box.

**Comment by abompard** [comment]
Thanks for the report! At first glance I think the culprit is [_form_macros.html](https://github.com/fedora-infra/noggin/blob/03d1896ac1d335e4ed10cce2395586153d7a7d01/noggin/templates/_form_macros.html#L18).

**Comment by himanshu007-creator** [comment]
Hi, i would like to work on this issue, Kindly guide me what changes need to be done😄

**Comment by jaller94** [comment]
@himanshu007-creator Labels of BooleanField need the `for` property which needs to match the `id` property of the input.

According to [this code](https://github.com/wtforms/wtforms/blob/a55be54c0b8487f81e8c0f61279818ada0bd2075/src/wtforms/fields/core.py#L142) the value is stored in `input.id`.

I posted a quick guess of what could be the fix in #660.

Someone with a working development environment should verify that this fixes the problem by going through the "Steps to reproduce the issue" in the first post of this thread. If my PR doesn't solve the problem, it could get improved or another way should be found.

**Comment by ADHIKSHA** [comment]
Hey, I will like to work on this issue. Is there anything I can do?
