### ISSUE TITLE
(S) As a AAA developer I want the be able to automate the release notes so that I don't spend a lot of time preparing a release

### ISSUE THREAD

**Issue by abompard** [fedora-infra/noggin#66]
## Acceptance Criteria

* Project is configured to use towncrier to manage the release notes.

## DOD
As above

**Comment by abompard** [comment]
Blocked by PR #62 (US #63) because it needs the setup that is done there

**Comment by sfinn85** [comment]
Hi @abompard , 

Just for my understanding PR #62, we are reverting back to " quotes instead of ' and #63 needs to be reviewed by a team member? When these are complete are you unblocked?

**Comment by abompard** [comment]
In a Github board we can put issues (in our cases user stories) *and* PRs. In the case of user story #63, it should be fixed by PR #62 which is ready for review. In the board I have put only the user story, not the pull request, although it's the pull request that is ready for review and not the user story (since we have already agreed on it).
I don't know what's best to do workflow-wise and information-wise, whether it's better to have only issues in the board or if we mix issues and PRs (which may make more sense since it's the PRs that need review).
I have no personal perference on that subject.
To answer your second question, when PR #62 is merged then US #63 will be closed and I'll be unblocked.

**Comment by sfinn85** [comment]
Hi @abompard great work!

@relrod when you closed this ticket, does that mean you have reviewed it, happy to accept and see the user story as done?
