### ISSUE TITLE
Show email addresses in the public profile

### ISSUE THREAD

**Issue by FrostyX** [fedora-infra/noggin#667]
Either I cannot find email addresses in the public profile or they are not displayed. In that case, please show them.

If I want to communicate with somebody via email, I need to go to the old https://admin.fedoraproject.org/accounts and find their profile there.

Displaying the email information shouldn't be a problem since it is available via API anyways.

**Comment by abompard** [comment]
Agreed, duplicate of #568

**Comment by FrostyX** [comment]
Ah, sorry @abompard,
I missed the original issue.
