### ISSUE TITLE
Broken encoding of some human names

### ISSUE THREAD

**Issue by FrostyX** [fedora-infra/noggin#686]
Please see `hguemar`'s profile.
https://accounts.fedoraproject.org/user/hguemar/

His real name is rendered incorrectly - `HaÃ¯kel GuÃ©mar`. Also, if you get the user profile via API

```python
from fasjson_client import Client
client = Client("https://fasjson.fedoraproject.org/")
hguemar = client.get_user(username="hguemar")
print(hguemar.result["human_name"])
```

```
HaÃ¯kel GuÃ©mar
```

The old FAS shows the name correctly https://admin.fedoraproject.org/accounts/user/view/hguemar and also `/msg zodbot fasinfo hguemar` shows the name correctly.

**Comment by abompard** [comment]
Thanks for the report, the data in IPA was wrong. It's probably an error during the migration from FAS, I fixed it.
(until recently zodbot was still talking to the old FAS)

**Comment by FrostyX** [comment]
Thank you @abompard
