### ISSUE TITLE
(S)Wireframe the login form

### ISSUE THREAD

**Issue by sfinn85** [fedora-infra/noggin#7]

**Comment by ryanlerch** [comment]
First pass at the signin / signup page,

![signin-signup](https://user-images.githubusercontent.com/592259/71964706-e12c4e00-3249-11ea-908f-b68f84662265.png)

**Comment by StephenCoady** [comment]
Looks good to me. The only thing I would add is that we will probably have an email field in the new account section.

**Comment by sfinn85** [comment]
Looks good Ryan! Thank you. Your feedback is spot on Stephen, we would need email. In addition to that,something so small.. could you add Caps on n for " New and " S" sign , U " username and " P" password.

Can you update it and add revised version here. 

Note: I never got a chance to check the thread for the fields we were going to drop and include but this does look good.  @relrod is this as expected? 

Thanks Ryan

**Comment by ryanlerch** [comment]
Sorry, i updated the wireframe on the wiki, but didnt put it here as well.

![signin-signup](https://user-images.githubusercontent.com/592259/72424262-6cb95800-37d1-11ea-8383-c181d0f61b0d.png)

**Comment by sfinn85** [comment]
Hi @ryanlerch 

Thanks a mill, looks good, I like the intro :). Just to note, I presume we will be adding help text here if a username is taken, email is incorrect etc. 

@StephenCoady  from a user perspective. Are you happy to accept/ approve?

**Comment by StephenCoady** [comment]
Yep looks good to me.

**Comment by sfinn85** [comment]
Excellent, I will move to done :).. if you are happy to approve going forward, you can just move it to done :)

Thanks all
