### ISSUE TITLE
No error message on unsuccessful login

### ISSUE THREAD

**Issue by FrostyX** [fedora-infra/noggin#713]
The auth form doesn't show a user-friendly (or any) error when the login is not successful. I tried to log in (with a wrong password) through various Fedora sites such as Copr, Bodhi, and Pagure. Each time I got a different response but not once something I would expect.

Copr:
1. Go to https://copr.fedorainfracloud.org/ and click on the "log in" button in the top right
2. Type wrong login information and submit the form
3. You get redirected to the same https://id.fedoraproject.org/ page without any error message

Bodhi:
1. Go to https://bodhi.fedoraproject.org/ and click on the "log in" button in the top right
2. Type wrong login information and submit the form
3. You get redirected back to https://bodhi.fedoraproject.org, not logged-in, and without any error message

Pagure:
1. Go to https://pagure.io/ and click on the "log in" button in the top right
2. Type wrong login information and submit the form
3. You get redirected to a _blank_ page saying "OpenID request was cancelled"

IMHO none of this should happen, the third-party services using FAS login shouldn't handle the failed-auth case, the FAS/noggin/login-form should. We should get redirected back to the original service only after successfully authenticated or when intentionally canceling the auth process with some button.

**Comment by abompard** [comment]
Thanks for reporting, but this is an issue with Ipsilon. Could you copy and paste your message [as an Ipsilon ticket](https://pagure.io/ipsilon/issues) please?
Thanks.

**Comment by FrostyX** [comment]
Thank you @abompard,
reported here https://pagure.io/ipsilon/issue/357
