### ISSUE TITLE
Logging in by email + password

### ISSUE THREAD

**Issue by FrostyX** [fedora-infra/noggin#714]
In Copr, we occasionally get reports like these:
https://bugzilla.redhat.com/show_bug.cgi?id=1943925

People are trying to log in by using their email + password instead of username + password and weird redirects are happening. We could discuss which side is to blame for the unnecessary redirects but I would say that is not what we should focus on.

IMHO the login should be properly validated and we should not get past the auth form when trying to log in with email + password. I would expect to be redirected back to Copr only when the authentication was successful or when I decide to abort it.

Maybe this is a duplicate of #713, in that case, my apologies for a redundant issue. I am submitting it separate in case you think it is more to it than what #713 is about.

**Comment by abompard** [comment]
Thanks for reporting, but this is an issue with Ipsilon. Could you copy and paste your message [as an Ipsilon ticket](https://pagure.io/ipsilon/issues) please?
Thanks.

**Comment by FrostyX** [comment]
Thank you @abompard,
reported here https://pagure.io/ipsilon/issue/358
