### ISSUE TITLE
OTP field in the auth form

### ISSUE THREAD

**Issue by FrostyX** [fedora-infra/noggin#715]
In Copr, we have at least one person each week who is confused about where to put OTP in the auth form. I think there are two reasons for this (which we found when investigating the issue with the person).

1. The login form on https://accounts.fedoraproject.org/ has three fields (Username, password, and OTP) while the login form on https://id.fedoraproject.org has only two (Username and password + OTP)
2. The login form on https://id.fedoraproject.org clearly shows that the field is password + OTP but it is indicated only in the field placeholder and therefore people who auto-fill the form don't see this information.

I don't know what is the preferred solution for this, whether adding the third field for OTP as https://accounts.fedoraproject.org/ does or displaying that the field is password + OTP somewhere (else) outside the field placeholder. Either one is fine with me but the current situation seems to be not sufficient.

**Comment by abompard** [comment]
Having the label outside the placeholder seems like a good idea. We tried having a separate field for OTP in Ipsilon but it proved more complex than expected. Could you open the ticket [in Ipsilon](https://pagure.io/ipsilon/issues) please?
Thanks.

**Comment by FrostyX** [comment]
Thank you @abompard,
reported here https://pagure.io/ipsilon/issue/359
