### ISSUE TITLE
400 Error Description

### ISSUE THREAD

**Issue by lgriffin** [fedora-infra/noggin#752]
I got a 400 Bad Request error when I authenticated with the wrong credentials. The error that comes back is not descriptive and doesn't grammatically flow. It currently says:

'User not authenticated at continue'

My assumption is it is not authenticated at the continue step....it might just need one word added or replace at with to.

**Comment by abompard** [comment]
This is actually an Ipsilon issue, it's the web app that handles OIDC & SAML authentication. Could you open the ticket [on Ipsilon's tracker](https://pagure.io/ipsilon/new_issue) please? Thanks.

**Comment by lgriffin** [comment]
Super, I raised it there :)
