### ISSUE TITLE
constraints used for password requirements needs to be more stringent

### ISSUE THREAD

**Issue by james02135** [fedora-infra/noggin#82]

**Comment by james02135** [comment]
Does it make sense to hunt down where the constraints are actually written  - and change them, or just make our own?

**Comment by relrod** [comment]
Right now we just use the default constraints from FreeIPA. If these are insufficient, we can discuss, but they are tunable as IPA settings.

**Comment by relrod** [comment]
Going to close this for now, as this is ultimately a policy discussion and not really a portal discusison
