### ISSUE TITLE
Why can't I stay with different email address than Red Hat Bugzilla email address?

### ISSUE THREAD

**Issue by anoopcs9** [fedora-infra/noggin#826]
Recently I managed to change my email address at [Fedora Accounts](https://accounts.fedoraproject.org/) which is different from my Red Hat bugzilla email address. Since then I started receiving notification mail, everyday, from admin@fedoraproject.org indicating a mismatch in email addresses. Yes, I am a Fedora packager and the email tries to say that it is good to have another bugzilla account with updated email id or revert to older email id(matching current bugzilla account).

I already have my bugzilla account address updated correctly inside Fedora Accounts. Why is it necessary to have another bugzilla account with my other email id? Can someone explain?

**Comment by abompard** [comment]
Hello! Could you please open this ticket on [the Fedora Infra tracker](https://pagure.io/fedora-infrastructure/new_issue)? I think it's more related to the Fedora Infra installation of Noggin than to the software itself?
I could open it for you but then you would not be notified of updates, so it's better if you do it yourself.
Thanks!

**Comment by anoopcs9** [comment]
Fine.

Opened a [ticket](https://pagure.io/fedora-infrastructure/issue/10404) with Fedora Infra.Thanks for the pointer.
