### ISSUE TITLE
You shouldn't have to be on RedHat VPN to vagrant up

### ISSUE THREAD

**Issue by AdamSaleh** [fedora-infra/noggin#84]
When trying to run `vagrant up` I got `Could not resolve host: download.eng.brq.redhat.com`.

**Comment by abompard** [comment]
I'm almost never on the Red Hat VPN and I've never seen this error when doing vagrant up. I also don't see any reference to redhat.com in the Vagrant or Ansible files.

**Comment by relrod** [comment]
Yeah there's no reference to redhat at all. It sounds like download.fedoraproject.org sent you to a RH mirror for whatever reason. Are you doing this from a Red Hat office? In any case, if anything this is an infra bug or a bug for whoever set up that mirror at RH. Closing this.
