### ISSUE TITLE
Migrate to python-freeipa @1.0.0

### ISSUE THREAD

**Issue by StephenCoady** [fedora-infra/noggin#85]
Currently our application uses ~0.2 of python-freeipa. Recently this module released v1.0.0 which breaks/removes most of the endpoints we use within securitas. We should fix this by migrating securitas to either:

1) Use the new endpoints this updated version provides
2) Use the client_legacy provided by this new module to keep our code (mostly) the same.

There is also an official module, however we have not used this before so it might be a bigger change.

**Comment by relrod** [comment]
Fixed HEAD to use the legacy client. We should migrate to non-legacy, but I'll work on that after I get back from devconf.
