### ISSUE TITLE
Does noggin encourage non-FedoraProject.org deployment?

### ISSUE THREAD

**Issue by johnnyutahh** [fedora-infra/noggin#854]
Background: this discussion originated at [What to use in place of Fedora Wiki...for user-contrib docs](https://ask.fedoraproject.org/t/what-to-use-in-place-of-fedora-wiki-when-making-a-community-editable-document-reference/19740/11)...

**Summary: 2 questions**

1. Does `noggin` project intend to serve non-FedoraProject.org deployments?
2. What are the non-`noggin` FreeIPA-user-selfservice-portal alternatives?

**Details**

re: FreeIPA user-self-service portal...

Interesting, looks like Fedora created their own, very cool. This may be obvious, but since it's not explicitly stated, we feel it's best to ask: _Does the Fedora community (or whoever is leading this `noggin` effort) encourage others (like my team) to use it for their own projects?_

It's not clear if it's only targeted for fedoraproject dot org or if it's specifically built out for general use, but with the readthedocs site it sure seems like the latter. We could use such a thing (self-service portal), too. Environment would be an internal network, not exposed to the public.

A brief search does not initially find many other FreeIPA user-self-service portals. Mokey, Redtape... not a large user community. Maybe why Fedora rolled their own.

To this end: can `noggin` people share their non-`noggin` FreeIPA-user-portal history, references, notes, or thoughts?

**Comment by abompard** [comment]
Hey! Thanks for asking. While Noggin has been designed with the Fedora and CentOS use-cases in mind, it's also built to be usable with other installations of FreeIPA. The Fedora-specific values can be set in the configuration file.
Actually, unless they changed something recently, OpenSuSE already uses Noggin too. @Conan-Kudo could tell you more about this and how they diverge from the Fedora instance.

**Comment by johnnyutahh** [comment]
Thanks @abompard, helpful. When you mention "Fedora," "CentOS," and "OpenSuSE"... do you refer to their specific online _communities_ (eg: specific websites) or to any deployment made on said _operating system_?

In any case, I hope to hear more from @Conan-Kudo.

Thanks again!

**Comment by Conan-Kudo** [comment]
@abompard is referring to the communities.

The openSUSE instance is not live because of some other complications, but @hellcp and I worked with the team early on to ensure it was community agnostic. That said, the openSUSE deployment has FreeIPA currently on CentOS Stream and Noggin on Fedora from the Fedora packages.

Ipsilon is deployed on openSUSE Leap.

**Comment by korewaChino** [comment]
Ultramarine Project here! We also use noggin + FreeIPA for authentication, although we do use Keycloak instead of Ipsilon.

**Comment by abompard** [comment]
I'm closing this ticket, but feel free to reopen if you have further questions on this subject.
