### ISSUE TITLE
Wrong error message when creating a FAS Account with less than five/5 characters

### ISSUE THREAD

**Issue by 86ul** [fedora-infra/noggin#866]
Hello fellow users of Fedora,

Recently I tried to create a new FAS Account with a short name, but with the approved characters, namely `86ul`; just like here on GitHub. However, I could not do so, 'because'

> Only these characters are allowed: “a-z”, “0-9”, “-”.

Due to my relative short username, I figured out that I had less than the approved characters, but that error message was not shown. See also the attachment:
![20220209 - 091437 - 6446bc0a0408](https://user-images.githubusercontent.com/73539720/153180489-b7c64ed2-51ef-456b-80ee-8c5cd54adde7.jpg)

Is it therefore possible to show a correct error message, when someone creates an username with less than the approved of five/5 characters?

**Comment by abompard** [comment]
Your analysis is correct, it's a length issue and the message is misleading. Thanks.

**Comment by splace** [comment]
+1

(notice it also tells you directly a length of 3 is fine.)

**Comment by SerhiyAndryeyev** [comment]
I have the similar issue - I've created my account before limitation, and now I cant go into my account, because my username consist the point, and I cant change my username and even write on the ask.fedora
