### ISSUE TITLE
RFE: Support non-email "email" for groups

### ISSUE THREAD

**Issue by funnelfiasco** [fedora-infra/noggin#867]
In fedora-infra 10533, Kevin said [Noggin will not support a URL as a mailing list address](https://pagure.io/fedora-infrastructure/issue/10533#comment-780232) for groups. Since many groups use Fedora Discussion instead of mailing lists, it would be good to support that.

**Comment by abompard** [comment]
This seems doable, it would mean adding a property in the LDAP schema in https://github.com/fedora-infra/freeipa-fas, and displaying it in Noggin.
