### ISSUE TITLE
RFE: last login date

### ISSUE THREAD

**Issue by mattiaverga** [fedora-infra/noggin#879]
I am writing a [script](https://pagure.io/find-inactive-packagers) to find inactive users in Fedora `packager` group. Currently it fetches all users in the group, then check user activities in various places.
The [idea](https://pagure.io/fesco/issue/2759) is to find inactive account that may possible be hijacked.
As the number of packagers is quite high (over 2.5k) the script takes hours to complete.

Having a "last logged in" field may drastically reduce the time required by the script, as I can filter out users that have recently logged into their account. Is that something it can be added or there is some "privacy" or technical issue?

**Comment by abompard** [comment]
I don't think that this value is easily accessible in IPA. It would probably be a security or a privacy concern indeed.

**Comment by ryanlerch** [comment]
@mattiaverga is this still something we might need? or is this more of a fasjson issue rather than noggin itself?

**Comment by mattiaverga** [comment]
It would be nice to have, yes, but based on the previous reply where it seems hard to implement and can possibly have privacy/security concerns, I can also live without that and drop the request.
