### ISSUE TITLE
Unable to recreate account

### ISSUE THREAD

**Issue by tuxmaster5000** [fedora-infra/noggin#886]
I am affect of https://pagure.io/fedora-infrastructure/issue/10488.
But change the email address for the old account will not work, because it is logged.
Create an new will fail because the mail address is connect to the old one.
So I am not able to resolve the chicken egg problem.
I don't have another mail address that I can use for FAS.

**Comment by abompard** [comment]
Hello, are you still affected by this? Thanks.

**Comment by tuxmaster5000** [comment]
No, it was fixed, by the admin in the meantime
