### ISSUE TITLE
A user can't change their email address

### ISSUE THREAD

**Issue by abompard** [fedora-infra/noggin#95]
When I try to change my email address I get:
```
Insufficient access: Insufficient 'write' privilege to the 'mail' attribute of entry 'uid=abompard,cn=users,cn=accounts,dc=example,dc=com'.
```

A user should be allowed to change their email, I think.

**Comment by abompard** [comment]
Uh I can't reproduce this error now. Weird. Any idea where that could have come from?

**Comment by abompard** [comment]
Hmm nope it does fail and I can reproduce it now.

**Comment by abompard** [comment]
I have found a way to fix it: add the appropriate policy to the IPA server with the following command:
```
ipa selfservice-add "Users can manage their own email address" --attrs mail
```

I think we should add this policy to our setup, but I'm not sure what the best way to do it would be. Add the command to the FreeIPA ansible playbook? Add an update file in freeipa-fas? Something else?

**Comment by relrod** [comment]
@tiran advice here? Should this be done in the custom schema files or done using the built-in mechanism @abompard found?

**Comment by sfinn85** [comment]
Thanks for following up on this @relrod and @abompard .

**Comment by sfinn85** [comment]
Advice from @tiran .. needed. (s)
When we get it , we need to add AC  & DOD

**Comment by tiran** [comment]
A standard IPA user can only manage some of her/his attributes. As you have already figured out the ``mail`` attribute is not listed as self-serviceable attribute. The default list of serviceable attributes is: 

```
dn: $SUFFIX
changetype: modify
add: aci
aci: (targetattr = "userpassword || krbprincipalkey || sambalmpassword || sambantpassword")(version 3.0; acl "selfservice:Self can write own password"; allow (write) userdn="ldap:///self";)
aci: (targetattr = "givenname || sn || cn || displayname || title || initials || loginshell || gecos || homephone || mobile || pager || facsimiletelephonenumber || telephonenumber || street || roomnumber || l || st || postalcode || manager || secretary || description || carlicense || labeleduri || inetuserhttpurl || seealso || employeetype  || businesscategory || ou")(version 3.0;acl "selfservice:User Self service";allow (write) userdn = "ldap:///self";)
aci: (targetattr = "ipasshpubkey")(version 3.0;acl "selfservice:Users can manage their own SSH public keys";allow (write) userdn = "ldap:///self";)
aci: (targetattr = "usercertificate")(version 3.0;acl "selfservice:Users can manage their own X.509 certificates";allow (write) userdn = "ldap:///self";)
```

The command

```
ipa selfservice-add "Users can manage their own email address" --attrs mail
```

adds a new ACI

```
(targetattr = "mail")(version 3.0;acl "selfservice:Users can manage their own email address";allow (write) userdn = "ldap:///self";)
```

to the root of the IPA database. I can easily add the ACI to the freeipa-fas plugin so it gets auto-created on install and upgrade.

**Comment by abompard** [comment]
> I can easily add the ACI to the freeipa-fas plugin so it gets auto-created on install and upgrade.

I think that would be ideal, thanks @tiran

**Comment by sfinn85** [comment]
Hi @tiran 

Your a hard man to track down :). I can't find you on IRC, chat , email.. its probably just me, still trying to figure out some things. 

Just want to thank you for your work on this and finding a solution.. virtual high five :) ! 

However, we are blocked until the ACI is added to the freeipa-fas plugin. Can you add it? If so when? As this has been open about 12 days, @abompard does have a workaround he can use if you don't have the capacity to carry out the above task. No pressure we just need to move this forward.

 If we don't hear from you by 1200 utc we will run with Aureliens work around.

Thanks again
Sarah

**Comment by sfinn85** [comment]
@abompard reviewed and confirmed this is done!
