### ISSUE TITLE
Impossible to add (multiple) GPG key(s)

### ISSUE THREAD

**Issue by abompard** [fedora-infra/noggin#96]
It's currently impossible in the user form to add one (or many) GPG keys.

**Comment by relrod** [comment]
@ryanlerch can fix this in his bootstrap redesign ;)

**Comment by abompard** [comment]
Yeah I just wanted to flag it so we don't forget.

**Comment by sfinn85** [comment]
A little bit more complicated than we thought. Client-side solution needs to be found.

**Comment by ryanlerch** [comment]
@abompard @relrod are there any examples of what exactly a GPG key ID will look like for this field?

is it a multi-line thing? or a simple one-line ID?

**Comment by relrod** [comment]
@sfinn85 complicated in what way?

@ryanlerch Each is a simple string `maxlength="16"`, but there can be multiple of them, so we just need a button to add extra fields for more keys.

**Comment by sfinn85** [comment]
Sprint 3 planning update: Keep it simple - ( S )
